import mongoose from 'mongoose';
import { MongoMemoryReplSet } from 'mongodb-memory-server';
import request from 'supertest';
import { afterAll, beforeAll, beforeEach, describe, expect, it } from 'vitest';
import { app } from '../src/app.js';
import { User } from '../src/models/User.js';
import { generateAccessToken } from '../src/utils/jwt.js';

let replicaSet; let sequence = 0;
const api = (path, token) => request(app).get(path).set('Authorization', `Bearer ${token}`);
const account = async (role = 'candidate') => { sequence += 1; const user = await User.create({ fullName: `${role} Analytics ${sequence}`, email: `analytics.${sequence}@talvix.test`, password: 'Strong!Pass123', role }); return { user, token: generateAccessToken(user.id) }; };

beforeAll(async () => { replicaSet = await MongoMemoryReplSet.create({ replSet: { count: 1 } }); await mongoose.connect(replicaSet.getUri()); await User.init(); });
beforeEach(async () => User.deleteMany({}));
afterAll(async () => { await mongoose.disconnect(); await replicaSet.stop(); });

describe('admin analytics API', () => {
  it('denies unauthenticated, candidate, recruiter, and inactive accounts while allowing admins', async () => { const candidate = await account(); const recruiter = await account('recruiter'); const admin = await account('admin'); await request(app).get('/api/v1/admin/analytics/overview').expect(401); await api('/api/v1/admin/analytics/overview', candidate.token).expect(403); await api('/api/v1/admin/analytics/overview', recruiter.token).expect(403); await User.updateOne({ _id: admin.user.id }, { isActive: false }); await api('/api/v1/admin/analytics/overview', admin.token).expect(401); });
  it('returns every private report family with a consistent empty-safe response and no personal data', async () => { const admin = await account('admin'); await account('candidate'); await account('recruiter'); for (const report of ['overview', 'users', 'candidates', 'recruiters', 'companies', 'jobs', 'applications', 'assessments', 'interviews', 'offers', 'documents', 'notifications', 'health']) { const response = await api(`/api/v1/admin/analytics/${report}?preset=last-7-days`, admin.token).expect(200); expect(response.body.success).toBe(true); expect(response.body.data.range).toMatchObject({ preset: 'last-7-days', interval: 'day', timezone: 'UTC' }); expect(response.body.data).toHaveProperty('summary'); expect(response.body.data).toHaveProperty('series'); expect(response.body.data).toHaveProperty('breakdowns'); expect(response.body.data).toHaveProperty('generatedAt'); expect(JSON.stringify(response.body)).not.toMatch(/analytics\.\d+@|password|phone|publicId|secureUrl|meetingUrl|approvalComments|candidateSnapshot/i); } });
  it('validates ranges, intervals, filters, and returns previous comparison without NaN', async () => { const admin = await account('admin'); await api('/api/v1/admin/analytics/users?from=2026-07-19T00:00:00.000Z', admin.token).expect(400); await api('/api/v1/admin/analytics/users?from=2026-07-20T00:00:00.000Z&to=2026-07-19T00:00:00.000Z', admin.token).expect(400); await api('/api/v1/admin/analytics/users?interval=minute', admin.token).expect(400); await api('/api/v1/admin/analytics/users?unknown=true', admin.token).expect(400); const response = await api('/api/v1/admin/analytics/users?preset=last-30-days&role=admin', admin.token).expect(200); expect(response.body.data.summary.registrations).toEqual(expect.objectContaining({ value: expect.any(Number), previous: expect.any(Number), changePercent: expect.any(Number) })); expect(JSON.stringify(response.body)).not.toMatch(/NaN|Infinity/); });
  it('exports bounded aggregate JSON and injection-safe CSV with sanitized filenames', async () => { const admin = await account('admin'); const json = await api('/api/v1/admin/analytics/export?report=users&format=json', admin.token).expect(200); expect(json.headers['content-disposition']).toMatch(/^attachment; filename="talvix-users-\d{4}-\d{2}-\d{2}\.json"$/); expect(JSON.stringify(json.body)).not.toContain(admin.user.email); const csv = await api('/api/v1/admin/analytics/export?report=overview&format=csv', admin.token).expect(200); expect(csv.headers['content-type']).toMatch(/text\/csv/); expect(csv.text).toMatch(/^metric,value/); await api('/api/v1/admin/analytics/export?report=private-users&format=csv', admin.token).expect(400); });
  it('returns a secret-free platform health summary', async () => { const admin = await account('admin'); const response = await api('/api/v1/admin/analytics/health', admin.token).expect(200); expect(response.body.data.summary).toEqual(expect.objectContaining({ databaseState: 'connected', storageProvider: expect.any(String), uploadsEnabled: expect.any(Boolean), uptimeSeconds: expect.any(Number), nodeVersion: expect.any(String) })); expect(JSON.stringify(response.body)).not.toMatch(/MONGODB_URI|JWT_|CLOUDINARY_|RESEND_|apiSecret|localhost|filesystem/i); });
});
