import mongoose from 'mongoose';
import { MongoMemoryReplSet } from 'mongodb-memory-server';
import request from 'supertest';
import { afterAll, beforeAll, beforeEach, describe, expect, it } from 'vitest';
import { app } from '../src/app.js';
import { Application } from '../src/models/Application.js';
import { Assessment } from '../src/models/Assessment.js';
import { AssessmentAssignment } from '../src/models/AssessmentAssignment.js';
import { AssessmentAttempt } from '../src/models/AssessmentAttempt.js';
import { Company } from '../src/models/Company.js';
import { Question } from '../src/models/Question.js';
import { RecruiterProfile } from '../src/models/RecruiterProfile.js';
import { User } from '../src/models/User.js';
import { generateAccessToken } from '../src/utils/jwt.js';
let replicaSet; let sequence = 0; const permissions = ['assessments.view', 'assessments.manage', 'assessments.assign', 'assessments.review'];
const api = (method, path, token) => request(app)[method](path).set('Authorization', `Bearer ${token}`);
const account = async (role) => { sequence += 1; const user = await User.create({ fullName: `${role} ${sequence}`, email: `${role}.${sequence}@assessment.test`, password: 'Strong!Pass123', role }); return { user, token: generateAccessToken(user.id) }; };
const recruiter = async () => { const owner = await account('recruiter'); const company = await Company.create({ name: `Assessment ${sequence}`, slug: `assessment-${sequence}`, owner: owner.user.id, verificationStatus: 'verified', isActive: true, teamMembers: [{ recruiter: owner.user.id, role: 'owner', permissions, status: 'active' }] }); await RecruiterProfile.create({ user: owner.user.id, company: company.id, isApproved: true, isCompanyOwner: true, permissions }); return { ...owner, company }; };
const choiceBody = () => ({ type: 'single-choice', title: 'Node runtime', prompt: 'Which runtime?', difficulty: 'easy', defaultMarks: 10, options: [{ id: 'node', text: 'Node.js' }, { id: 'browser', text: 'Browser' }], correctAnswer: { optionId: 'node' }, explanation: 'Node.js is a runtime.' });
const createPublished = async (owner, question) => { const created = await api('post', '/api/v1/assessments', owner.token).send({ title: 'Backend evidence', type: 'technical', durationMinutes: 30, passingPercentage: 60 }).expect(201); const id = created.body.data.assessment._id; await api('post', `/api/v1/assessments/manage/${id}/questions`, owner.token).send({ questionId: question.id, marks: 10 }).expect(200); await api('patch', `/api/v1/assessments/manage/${id}/publish`, owner.token).expect(200); return Assessment.findById(id); };
const applicationFor = async (owner, candidate) => Application.create({ candidate: candidate.user.id, candidateProfile: new mongoose.Types.ObjectId(), job: new mongoose.Types.ObjectId(), company: owner.company.id, applicationNumber: `TVX-ASSESS-${sequence}-${Date.now()}`, status: 'shortlisted', candidateSnapshot: { fullName: candidate.user.fullName }, jobSnapshot: { title: 'Engineer' }, skillMatch: { score: 0, matchedSkills: [], missingRequiredSkills: [], breakdown: [] } });
beforeAll(async () => { replicaSet = await MongoMemoryReplSet.create({ replSet: { count: 1 } }); await mongoose.connect(replicaSet.getUri()); await Promise.all([User.init(), RecruiterProfile.init(), Company.init(), Application.init(), Question.init(), Assessment.init(), AssessmentAssignment.init(), AssessmentAttempt.init()]); });
beforeEach(async () => { await Promise.all(Object.values(mongoose.connection.collections).map((collection) => collection.deleteMany({}))); }); afterAll(async () => { await mongoose.disconnect(); await replicaSet.stop(); });

describe('assessment question and assessment management', () => {
  it('validates answer references, enforces company scope, publishes, and freezes used questions', async () => { const owner = await recruiter(); const outsider = await recruiter(); await api('post', '/api/v1/assessments/questions', owner.token).send({ ...choiceBody(), correctAnswer: { optionId: 'missing' } }).expect(400); const created = await api('post', '/api/v1/assessments/questions', owner.token).send(choiceBody()).expect(201); const id = created.body.data.question._id; await api('get', `/api/v1/assessments/questions/${id}`, outsider.token).expect(404); const question = await Question.findById(id); const assessment = await createPublished(owner, question); expect(assessment.totalMarks).toBe(10); expect((await Question.findById(id)).usageCount).toBe(1); await api('patch', `/api/v1/assessments/questions/${id}`, owner.token).send({ prompt: 'Changed' }).expect(409); await api('patch', `/api/v1/assessments/manage/${assessment.id}`, owner.token).send({ title: 'Changed' }).expect(409); const clone = await api('post', `/api/v1/assessments/questions/${id}/clone`, owner.token).expect(201); expect(clone.body.data.question.usageCount).toBe(0); });
  it('rejects duplicate questions and publishing an empty assessment', async () => { const owner = await recruiter(); const question = await Question.create({ ...choiceBody(), company: owner.company.id, createdBy: owner.user.id }); const created = await api('post', '/api/v1/assessments', owner.token).send({ title: 'Draft', type: 'general', durationMinutes: 10, passingPercentage: 50 }).expect(201); const id = created.body.data.assessment._id; await api('patch', `/api/v1/assessments/manage/${id}/publish`, owner.token).expect(400); await api('post', `/api/v1/assessments/manage/${id}/questions`, owner.token).send({ questionId: question.id, marks: 5 }).expect(200); await api('post', `/api/v1/assessments/manage/${id}/questions`, owner.token).send({ questionId: question.id, marks: 5 }).expect(409); });
});

describe('assignment, candidate attempt, and evaluation', () => {
  it('preserves a secret snapshot, autosaves idempotently, grades, and completes the application', async () => { const owner = await recruiter(); const candidate = await account('candidate'); const question = await Question.create({ ...choiceBody(), company: owner.company.id, createdBy: owner.user.id }); const assessment = await createPublished(owner, question); const application = await applicationFor(owner, candidate); const assigned = await api('post', '/api/v1/assessments/assignments', owner.token).send({ assessmentId: assessment.id, applicationId: application.id, availableFrom: new Date(Date.now() - 1000), expiresAt: new Date(Date.now() + 3600000) }).expect(201); const assignmentId = assigned.body.data.assignment._id; expect((await Application.findById(application.id)).status).toBe('assessment-pending'); const detail = await api('get', `/api/v1/assessments/assignments/me/${assignmentId}`, candidate.token).expect(200); expect(detail.body.data.assignment.assessmentSnapshot).toBeUndefined(); const started = await api('post', `/api/v1/assessments/assignments/me/${assignmentId}/start`, candidate.token).expect(201); const attempt = started.body.data.attempt; expect(attempt.questions[0].correctAnswer).toBeUndefined(); expect(attempt.questions[0].explanation).toBeUndefined(); await api('patch', `/api/v1/assessments/attempts/me/${attempt.id}/answers`, candidate.token).send({ questionId: question.id, answer: 'node' }).expect(200); await api('patch', `/api/v1/assessments/attempts/me/${attempt.id}/answers`, candidate.token).send({ questionId: question.id, answer: 'node', flaggedForReview: true }).expect(200); expect((await AssessmentAttempt.findById(attempt.id)).answers).toHaveLength(1); const submitted = await api('post', `/api/v1/assessments/attempts/me/${attempt.id}/submit`, candidate.token).expect(200); expect(submitted.body.data.attempt.status).toBe('completed'); await api('post', `/api/v1/assessments/attempts/me/${attempt.id}/submit`, candidate.token).expect(200); expect((await Application.findById(application.id)).status).toBe('assessment-completed'); await api('get', `/api/v1/assessments/attempts/me/${attempt.id}/result`, candidate.token).expect(403); await api('patch', `/api/v1/assessments/assignments/manage/${assignmentId}/release-result`, owner.token).expect(200); const released = await api('get', `/api/v1/assessments/attempts/me/${attempt.id}/result`, candidate.token).expect(200); expect(released.body.data.result.score).toBe(10); expect(JSON.stringify(released.body)).not.toContain('correctAnswer'); expect(JSON.stringify(released.body)).not.toContain('isCorrect'); });
  it('prevents early starts, duplicate active assignments, and cross-candidate access', async () => { const owner = await recruiter(); const candidate = await account('candidate'); const other = await account('candidate'); const question = await Question.create({ ...choiceBody(), company: owner.company.id, createdBy: owner.user.id }); const assessment = await createPublished(owner, question); const application = await applicationFor(owner, candidate); const payload = { assessmentId: assessment.id, applicationId: application.id, availableFrom: new Date(Date.now() + 3600000), expiresAt: new Date(Date.now() + 7200000) }; const assigned = await api('post', '/api/v1/assessments/assignments', owner.token).send(payload).expect(201); await api('post', '/api/v1/assessments/assignments', owner.token).send(payload).expect(409); await api('post', `/api/v1/assessments/assignments/me/${assigned.body.data.assignment._id}/start`, candidate.token).expect(409); await api('get', `/api/v1/assessments/assignments/me/${assigned.body.data.assignment._id}`, other.token).expect(404); });
});
