import mongoose from 'mongoose';
import { MongoMemoryReplSet } from 'mongodb-memory-server';
import request from 'supertest';
import { afterAll, beforeAll, beforeEach, describe, expect, it } from 'vitest';
import { app } from '../src/app.js';
import { AssessmentAssignment } from '../src/models/AssessmentAssignment.js';
import { AssessmentAttempt } from '../src/models/AssessmentAttempt.js';
import { Company } from '../src/models/Company.js';
import { Document } from '../src/models/Document.js';
import { FileUploadSession } from '../src/models/FileUploadSession.js';
import { RecruiterProfile } from '../src/models/RecruiterProfile.js';
import { StorageReservation } from '../src/models/StorageReservation.js';
import { User } from '../src/models/User.js';
import { UserStorageUsage } from '../src/models/UserStorageUsage.js';
import { resetMemoryStorage } from '../src/services/fileStorageProvider.service.js';

let replicaSet; let sequence = 0;
const auth = (method, path, token) => request(app)[method](path).set('Authorization', `Bearer ${token}`);
const register = async (role) => { sequence += 1; const response = await request(app).post('/api/v1/auth/register').send({ fullName: `${role} Assessment ${sequence}`, email: `assessment-doc.${sequence}@talvix.test`, password: 'Strong!Pass123', role }).expect(201); return { token: response.body.data.accessToken, id: response.body.data.user._id }; };
const recruiter = async (permissions) => { const account = await register('recruiter'); const company = await Company.create({ name: `Assessment Company ${sequence}`, slug: `assessment-company-${sequence}`, owner: account.id, verificationStatus: 'verified', isActive: true, teamMembers: [{ recruiter: account.id, permissions, status: 'active' }] }); await RecruiterProfile.updateOne({ user: account.id }, { company: company.id, isApproved: true, permissions }); return { ...account, company }; };
const makeAttempt = async (candidate, company, configuration, overrides = {}) => { const attachmentSnapshot = { ...configuration, allowedMimeTypes: [...configuration.allowedMimeTypes] }; const assignment = await AssessmentAssignment.create({ assessment: new mongoose.Types.ObjectId(), assessmentVersion: 1, assessmentSnapshot: { title: 'Snapshot', durationMinutes: 60, maximumAttempts: 1, attachments: attachmentSnapshot, questions: [] }, application: new mongoose.Types.ObjectId(), candidate: candidate.id, company, assignedBy: new mongoose.Types.ObjectId(), status: overrides.assignmentStatus ?? 'in-progress', availableFrom: new Date(Date.now() - 60000), expiresAt: overrides.assignmentExpired ? new Date(Date.now() - 1000) : new Date(Date.now() + 3600000) }); const attempt = await AssessmentAttempt.create({ assignment: assignment.id, assessment: assignment.assessment, application: assignment.application, candidate: candidate.id, company, attemptNumber: 1, status: overrides.attemptStatus ?? 'in-progress', startedAt: new Date(), expiresAt: overrides.attemptExpired ? new Date(Date.now() - 1000) : new Date(Date.now() + 1800000) }); return { assignment, attempt }; };
const session = async (candidate, attempt) => (await auth('post', '/api/v1/documents/upload-session', candidate.token).send({ category: 'assessment-attachment', entityType: 'assessment-attempt', entityId: String(attempt.id), purpose: 'Assessment evidence' }).expect(201)).body.data.uploadSession.id;
const upload = (candidate, attempt, uploadSession, bytes = Buffer.from('%PDF-1.4\nEvidence'), mime = 'application/pdf') => auth('post', `/api/v1/documents/assessments/attempts/${attempt.id}`, candidate.token).field('uploadSessionId', uploadSession).field('purpose', 'Assessment evidence').attach('file', bytes, { filename: mime === 'text/plain' ? 'evidence.txt' : 'evidence.pdf', contentType: mime });
const enabled = { enabled: true, maximumFiles: 1, maximumFileBytes: 1024, maximumTotalBytes: 1024, allowedMimeTypes: ['application/pdf'] };

beforeAll(async () => { replicaSet = await MongoMemoryReplSet.create({ replSet: { count: 1 } }); await mongoose.connect(replicaSet.getUri()); await Promise.all([User.init(), RecruiterProfile.init(), Company.init(), AssessmentAssignment.init(), AssessmentAttempt.init(), Document.init(), FileUploadSession.init(), UserStorageUsage.init(), StorageReservation.init()]); });
beforeEach(async () => { await Promise.all([User.deleteMany({}), RecruiterProfile.deleteMany({}), Company.deleteMany({}), AssessmentAssignment.deleteMany({}), AssessmentAttempt.deleteMany({}), Document.deleteMany({}), FileUploadSession.deleteMany({}), UserStorageUsage.deleteMany({}), StorageReservation.deleteMany({})]); resetMemoryStorage(); });
afterAll(async () => { await mongoose.disconnect(); await replicaSet.stop(); });

describe('assessment attempt documents', () => {
  it('uses immutable enabled snapshot rules and derives company', async () => { const candidate = await register('candidate'); const manager = await recruiter(['documents.view', 'assessments.view']); const { assignment, attempt } = await makeAttempt(candidate, manager.company.id, enabled); enabled.enabled = false; const uploadSession = await session(candidate, attempt); const response = await upload(candidate, attempt, uploadSession).expect(201); enabled.enabled = true; const stored = await Document.findById(response.body.data.document.id); expect(stored.company.toString()).toBe(manager.company.id); expect(assignment.assessmentSnapshot.attachments.enabled).toBe(true); const secondSession = await session(candidate, attempt); await upload(candidate, attempt, secondSession, Buffer.from('%PDF-1.4\nSecond')).expect(413); const listed = await auth('get', `/api/v1/documents/manage/assessments/attempts/${attempt.id}`, manager.token).expect(200); expect(listed.body.data.documents).toHaveLength(1); await auth('get', `/api/v1/documents/manage/assessments/attempts/${attempt.id}/${stored.id}/download`, manager.token).expect(200); });
  it('rejects disabled, disallowed, oversized, submitted, cancelled, and expired uploads', async () => { const candidate = await register('candidate'); const company = new mongoose.Types.ObjectId(); for (const [configuration, overrides, mime, expected] of [[{ ...enabled, enabled: false }, {}, 'application/pdf', 409], [enabled, {}, 'text/plain', 400], [{ ...enabled, maximumFileBytes: 10 }, {}, 'application/pdf', 413], [enabled, { attemptStatus: 'submitted' }, 'application/pdf', 409], [enabled, { assignmentStatus: 'cancelled' }, 'application/pdf', 409], [enabled, { assignmentExpired: true }, 'application/pdf', 409]]) { const { attempt } = await makeAttempt(candidate, company, configuration, overrides); const uploadSession = await session(candidate, attempt); const bytes = configuration.maximumFileBytes === 10 ? Buffer.from('%PDF-1.4\nThis is larger than ten bytes') : Buffer.from('%PDF-1.4\nX'); await upload(candidate, attempt, uploadSession, bytes, mime).expect(expected); } });
  it('enforces candidate ownership and recruiter permissions/company scope', async () => { const owner = await register('candidate'); const other = await register('candidate'); const manager = await recruiter(['documents.view', 'assessments.view']); const denied = await recruiter(['assessments.view']); const outsider = await recruiter(['documents.view', 'assessments.view']); const { attempt } = await makeAttempt(owner, manager.company.id, enabled); const uploadSession = await session(owner, attempt); const response = await upload(owner, attempt, uploadSession).expect(201); await auth('get', `/api/v1/documents/assessments/attempts/${attempt.id}`, other.token).expect(404); await auth('get', `/api/v1/documents/manage/assessments/attempts/${attempt.id}`, denied.token).expect(403); await auth('get', `/api/v1/documents/manage/assessments/attempts/${attempt.id}`, outsider.token).expect(404); await Document.updateOne({ _id: response.body.data.document.id }, { status: 'quarantined', 'malwareScan.status': 'suspicious' }); await auth('get', `/api/v1/documents/manage/assessments/attempts/${attempt.id}/${response.body.data.document.id}/download`, manager.token).expect(404); });
});
