import mongoose from 'mongoose';
import { MongoMemoryReplSet } from 'mongodb-memory-server';
import request from 'supertest';
import { afterAll, beforeAll, beforeEach, describe, expect, it } from 'vitest';
import { app } from '../src/app.js';
import { Application } from '../src/models/Application.js';
import { CandidateProfile } from '../src/models/CandidateProfile.js';
import { Company } from '../src/models/Company.js';
import { Document } from '../src/models/Document.js';
import { FileUploadSession } from '../src/models/FileUploadSession.js';
import { Notification } from '../src/models/Notification.js';
import { NotificationOutbox } from '../src/models/NotificationOutbox.js';
import { RecruiterProfile } from '../src/models/RecruiterProfile.js';
import { StorageReservation } from '../src/models/StorageReservation.js';
import { User } from '../src/models/User.js';
import { UserStorageUsage } from '../src/models/UserStorageUsage.js';
import { processOutboxBatch } from '../src/services/notificationOutbox.service.js';
import { resetMemoryStorage } from '../src/services/fileStorageProvider.service.js';

let replicaSet; let sequence = 0;
const api = (method, path, token) => request(app)[method](path).set('Authorization', `Bearer ${token}`);
const register = async (role) => { sequence += 1; const response = await request(app).post('/api/v1/auth/register').send({ fullName: `${role} Document Event ${sequence}`, email: `document.event.${sequence}@talvix.test`, password: 'Strong!Pass123', role }).expect(201); return { token: response.body.data.accessToken, user: response.body.data.user }; };
const profileRecruiter = (actor, company, permissions, approved = true) => RecruiterProfile.updateOne({ user: actor.user._id }, { company, isApproved: approved, permissions });
const uploadSession = async (candidate, application, category = 'certificate') => (await api('post', '/api/v1/documents/upload-session', candidate.token).send({ category, entityType: 'application', entityId: application.id, purpose: category }).expect(201)).body.data.uploadSession.id;
const upload = (candidate, application, sessionId, suffix = '') => api('post', `/api/v1/documents/applications/${application.id}`, candidate.token).field('uploadSessionId', sessionId).field('purpose', `Certificate ${suffix}`).field('category', 'certificate').field('access', 'company-private').attach('file', Buffer.from(`%PDF-1.4\nCertificate ${suffix}`), { filename: `certificate-${suffix}.pdf`, contentType: 'application/pdf' });

beforeAll(async () => { replicaSet = await MongoMemoryReplSet.create({ replSet: { count: 1 } }); await mongoose.connect(replicaSet.getUri()); await Promise.all([User.init(), CandidateProfile.init(), RecruiterProfile.init(), Company.init(), Application.init(), Document.init(), FileUploadSession.init(), StorageReservation.init(), UserStorageUsage.init(), NotificationOutbox.init(), Notification.init()]); });
beforeEach(async () => { await Promise.all([User.deleteMany({}), CandidateProfile.deleteMany({}), RecruiterProfile.deleteMany({}), Company.deleteMany({}), Application.deleteMany({}), Document.deleteMany({}), FileUploadSession.deleteMany({}), StorageReservation.deleteMany({}), UserStorageUsage.deleteMany({}), NotificationOutbox.deleteMany({}), Notification.deleteMany({})]); resetMemoryStorage(); });
afterAll(async () => { await mongoose.disconnect(); await replicaSet.stop(); });

const setup = async () => { const candidate = await register('candidate'); const owner = await register('recruiter'); const verifier = await register('recruiter'); const noPermission = await register('recruiter'); const removed = await register('recruiter'); const unapproved = await register('recruiter'); const otherCompanyRecruiter = await register('recruiter'); const permissions = ['documents.view', 'documents.verify']; const company = await Company.create({ name: `Event Company ${sequence}`, slug: `event-company-${sequence}`, owner: owner.user._id, verificationStatus: 'verified', isActive: true, teamMembers: [{ recruiter: owner.user._id, permissions, status: 'active' }, { recruiter: verifier.user._id, permissions, status: 'active' }, { recruiter: verifier.user._id, permissions, status: 'active' }, { recruiter: noPermission.user._id, permissions: ['documents.view'], status: 'active' }, { recruiter: removed.user._id, permissions, status: 'removed' }, { recruiter: unapproved.user._id, permissions, status: 'active' }] }); await Promise.all([profileRecruiter(owner, company.id, permissions), profileRecruiter(verifier, company.id, permissions), profileRecruiter(noPermission, company.id, ['documents.view']), profileRecruiter(removed, company.id, permissions), profileRecruiter(unapproved, company.id, permissions, false)]); const other = await Company.create({ name: `Other Event Company ${sequence}`, slug: `other-event-company-${sequence}`, owner: otherCompanyRecruiter.user._id, verificationStatus: 'verified', isActive: true, teamMembers: [{ recruiter: otherCompanyRecruiter.user._id, permissions, status: 'active' }] }); await profileRecruiter(otherCompanyRecruiter, other.id, permissions); const candidateProfile = await CandidateProfile.findOne({ user: candidate.user._id }); const application = await Application.create({ candidate: candidate.user._id, candidateProfile: candidateProfile.id, job: new mongoose.Types.ObjectId(), company: company.id, applicationNumber: `TVX-EVENT-${sequence}`, status: 'submitted', candidateSnapshot: {}, jobSnapshot: { title: 'Engineer' }, skillMatch: { score: 0, matchedSkills: [], missingRequiredSkills: [], breakdown: [] } }); await NotificationOutbox.deleteMany({}); return { candidate, owner, verifier, noPermission, removed, unapproved, otherCompanyRecruiter, company, application }; };

describe('document notification recipients and isolation', () => {
  it('sends verification requests only to active approved permitted company recruiters with safe payloads', async () => { const context = await setup(); const sessionId = await uploadSession(context.candidate, context.application); const response = await upload(context.candidate, context.application, sessionId, 'request').expect(201); const event = await NotificationOutbox.findOne({ eventType: 'document.verification-requested' }).lean(); expect(event.recipientIds.map(String).sort()).toEqual([context.owner.user._id, context.verifier.user._id].sort()); expect(event.recipientIds.map(String)).not.toContain(context.candidate.user._id); const serialized = JSON.stringify(event); expect(serialized).not.toMatch(/checksum|buffer|secureUrl|signedUrl|publicId|cloudinary|identity.*number/i); expect(event.payload.documentId).toBe(response.body.data.document.id); });
  it('notifies only the owner on verification decisions, excludes private data, and remains idempotent through retries', async () => { const context = await setup(); const firstSession = await uploadSession(context.candidate, context.application); const first = await upload(context.candidate, context.application, firstSession, 'verified').expect(201); await api('patch', `/api/v1/documents/manage/verification/${first.body.data.document.id}/approve`, context.owner.token).send({ notes: 'Private reviewer note' }).expect(200); await api('patch', `/api/v1/documents/manage/verification/${first.body.data.document.id}/approve`, context.owner.token).send({ notes: 'Again' }).expect(404); const secondSession = await uploadSession(context.candidate, context.application); const second = await upload(context.candidate, context.application, secondSession, 'rejected').expect(201); await api('patch', `/api/v1/documents/manage/verification/${second.body.data.document.id}/reject`, context.owner.token).send({ reason: 'Please upload a readable copy.', notes: 'Private rejection detail' }).expect(200); await api('patch', `/api/v1/documents/manage/verification/${second.body.data.document.id}/reject`, context.owner.token).send({ reason: 'Again' }).expect(404); const decisions = await NotificationOutbox.find({ eventType: { $in: ['document.verified', 'document.rejected'] } }).lean(); expect(decisions).toHaveLength(2); for (const event of decisions) { expect(event.recipientIds.map(String)).toEqual([context.candidate.user._id]); expect(JSON.stringify(event)).not.toMatch(/Private|reviewedBy|publicId|checksum|secureUrl/i); } expect(decisions.find(({ eventType }) => eventType === 'document.rejected').payload.reason).toBe('Please upload a readable copy.'); await processOutboxBatch(20); await processOutboxBatch(20); expect(await Notification.countDocuments({ recipient: context.candidate.user._id, type: { $in: ['document-verified', 'document-rejected'] } })).toBe(2); });
});
