/* eslint-disable no-useless-escape */
import mongoose from 'mongoose';
import { MongoMemoryReplSet } from 'mongodb-memory-server';
import request from 'supertest';
import { afterAll, beforeAll, beforeEach, describe, expect, it } from 'vitest';
import { app } from '../src/app.js';
import { Application } from '../src/models/Application.js';
import { CandidateProfile } from '../src/models/CandidateProfile.js';
import { Company } from '../src/models/Company.js';
import { Document } from '../src/models/Document.js';
import { FileUploadSession } from '../src/models/FileUploadSession.js';
import { NotificationOutbox } from '../src/models/NotificationOutbox.js';
import { RecruiterProfile } from '../src/models/RecruiterProfile.js';
import { User } from '../src/models/User.js';
import { resetMemoryStorage } from '../src/services/fileStorageProvider.service.js';

let replicaSet; let sequence = 0;
const auth = (method, path, token) => request(app)[method](path).set('Authorization', `Bearer ${token}`);
const register = async (role) => { sequence += 1; const response = await request(app).post('/api/v1/auth/register').send({ fullName: `${role} Entity ${sequence}`, email: `entity.${sequence}@talvix.test`, password: 'Strong!Pass123', role }).expect(201); return { token: response.body.data.accessToken, user: response.body.data.user }; };
const createCompanyRecruiter = async (permissions, verificationStatus = 'verified') => { const account = await register('recruiter'); const company = await Company.create({ name: `Entity Company ${sequence}`, slug: `entity-company-${sequence}`, owner: account.user._id, verificationStatus, isActive: true, teamMembers: [{ recruiter: account.user._id, role: 'owner', permissions, status: 'active' }] }); await RecruiterProfile.updateOne({ user: account.user._id }, { company: company.id, isApproved: true, permissions }); return { ...account, company }; };
const session = async (account, category, entityType, entityId) => (await auth('post', '/api/v1/documents/upload-session', account.token).send({ category, entityType, entityId: String(entityId), purpose: category }).expect(201)).body.data.uploadSession.id;
const upload = (path, account, uploadSessionId, body, file = {}) => { const requestBuilder = auth('post', path, account.token).field('uploadSessionId', uploadSessionId).field('purpose', body.purpose ?? 'Supporting document'); if (body.category) requestBuilder.field('category', body.category); if (body.access) requestBuilder.field('access', body.access); return requestBuilder.attach('file', file.bytes ?? Buffer.from('%PDF-1.4\nEvidence'), { filename: file.name ?? 'evidence.pdf', contentType: file.mime ?? 'application/pdf' }); };

beforeAll(async () => { replicaSet = await MongoMemoryReplSet.create({ replSet: { count: 1 } }); await mongoose.connect(replicaSet.getUri()); await Promise.all([User.init(), CandidateProfile.init(), RecruiterProfile.init(), Company.init(), Application.init(), Document.init(), FileUploadSession.init(), NotificationOutbox.init()]); });
beforeEach(async () => { await Promise.all([User.deleteMany({}), CandidateProfile.deleteMany({}), RecruiterProfile.deleteMany({}), Company.deleteMany({}), Application.deleteMany({}), Document.deleteMany({}), FileUploadSession.deleteMany({}), NotificationOutbox.deleteMany({})]); resetMemoryStorage(); });
afterAll(async () => { await mongoose.disconnect(); await replicaSet.stop(); });

describe('company and application document integration', () => {
  it('synchronizes recruiter photos and verified-company logos', async () => { const recruiter = await createCompanyRecruiter(['documents.manage']); const profile = await RecruiterProfile.findOne({ user: recruiter.user._id }); const png = Buffer.from([0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a,1]); const photoSession = await session(recruiter, 'profile-photo', 'recruiter-profile', profile.id); await upload('/api/v1/documents/me/recruiter-profile-photo', recruiter, photoSession, {}, { bytes: png, name: 'photo.png', mime: 'image/png' }).expect(201); expect((await RecruiterProfile.findById(profile.id)).profilePhotoDocument).not.toBeNull(); const logoSession = await session(recruiter, 'company-logo', 'company', recruiter.company.id); const logo = await upload('/api/v1/documents/company/logo', recruiter, logoSession, {}, { bytes: png, name: 'logo.png', mime: 'image/png' }).expect(201); expect((await Company.findById(recruiter.company.id)).logoDocument.toString()).toBe(logo.body.data.document.id); expect(logo.body.data.document).not.toHaveProperty('storage'); });
  it('denies logo management without permission or company verification', async () => { const noPermission = await createCompanyRecruiter([]); const first = await session(noPermission, 'company-logo', 'company', noPermission.company.id); await upload('/api/v1/documents/company/logo', noPermission, first, {}, { bytes: Buffer.from([0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a]), name: 'logo.png', mime: 'image/png' }).expect(403); const unverified = await createCompanyRecruiter(['documents.manage'], 'pending'); const second = await session(unverified, 'company-logo', 'company', unverified.company.id); await upload('/api/v1/documents/company/logo', unverified, second, {}, { bytes: Buffer.from([0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a]), name: 'logo.png', mime: 'image/png' }).expect(403); });
  it('scopes pending application verification and protects private notes', async () => { const candidate = await register('candidate'); const recruiter = await createCompanyRecruiter(['documents.view', 'documents.verify']); const profile = await CandidateProfile.findOne({ user: candidate.user._id }); const application = await Application.create({ candidate: candidate.user._id, candidateProfile: profile.id, job: new mongoose.Types.ObjectId(), company: recruiter.company.id, applicationNumber: `APP-${sequence}`, status: 'submitted', candidateSnapshot: {}, jobSnapshot: { title: 'Engineer' }, skillMatch: { score: 0, matchedSkills: [], missingRequiredSkills: [], breakdown: [] } }); const uploadSession = await session(candidate, 'certificate', 'application', application.id); const response = await upload(`/api/v1/documents/applications/${application.id}`, candidate, uploadSession, { category: 'certificate', access: 'company-private' }).expect(201); const documentId = response.body.data.document.id; expect(response.body.data.document.verification.status).toBe('pending'); const queue = await auth('get', '/api/v1/documents/manage/verification', recruiter.token).expect(200); expect(queue.body.data.documents).toHaveLength(1); await auth('patch', `/api/v1/documents/manage/verification/${documentId}/reject`, recruiter.token).send({ reason: 'Please upload a clearer copy.', notes: 'Internal crop assessment.' }).expect(200); const candidateList = await auth('get', `/api/v1/documents/applications/${application.id}`, candidate.token).expect(200); expect(candidateList.body.data.documents[0].verification.reason).toBe('Please upload a clearer copy.'); expect(JSON.stringify(candidateList.body)).not.toContain('Internal crop assessment'); const outbox = await NotificationOutbox.find({ eventType: { $regex: '^document\.' } }); expect(outbox.length).toBeGreaterThanOrEqual(2); expect(JSON.stringify(outbox)).not.toMatch(/publicId|checksum|secureUrl|Internal crop assessment/); });
  it('hides company application documents from another company', async () => { const candidate = await register('candidate'); const owner = await createCompanyRecruiter(['documents.view', 'documents.verify']); const outsider = await createCompanyRecruiter(['documents.view', 'documents.verify']); const profile = await CandidateProfile.findOne({ user: candidate.user._id }); const application = await Application.create({ candidate: candidate.user._id, candidateProfile: profile.id, job: new mongoose.Types.ObjectId(), company: owner.company.id, applicationNumber: `APP-X-${sequence}`, status: 'submitted', candidateSnapshot: {}, jobSnapshot: { title: 'Engineer' }, skillMatch: { score: 0, matchedSkills: [], missingRequiredSkills: [], breakdown: [] } }); const uploadSession = await session(candidate, 'certificate', 'application', application.id); const response = await upload(`/api/v1/documents/applications/${application.id}`, candidate, uploadSession, { category: 'certificate', access: 'company-private' }).expect(201); await auth('get', `/api/v1/documents/manage/applications/${application.id}`, outsider.token).expect(404); await auth('get', `/api/v1/documents/manage/verification/${response.body.data.document.id}`, outsider.token).expect(404); });
});
