import mongoose from 'mongoose';
import { MongoMemoryReplSet } from 'mongodb-memory-server';
import { afterAll, beforeAll, beforeEach, describe, expect, it } from 'vitest';
import { Document } from '../src/models/Document.js';
import { FileUploadSession } from '../src/models/FileUploadSession.js';
import { StorageReservation } from '../src/models/StorageReservation.js';
import { UserStorageUsage } from '../src/models/UserStorageUsage.js';

let replicaSet;
const objectId = () => new mongoose.Types.ObjectId();
const documentData = ({ owner = objectId(), company, category, entityType, entityId = objectId() }) => ({ owner, ownerRole: 'candidate', uploadedBy: owner, company, category, purpose: category, entityType, entityId, originalFileName: `${category}.pdf`, displayName: category, extension: 'pdf', mimeType: 'application/pdf', mediaType: 'document', sizeBytes: 10, checksum: new mongoose.Types.ObjectId().toString().padEnd(64, 'a'), storage: { provider: 'memory', publicId: `talvix/candidate/${owner}/${objectId()}`, resourceType: 'raw' }, access: 'private', status: 'active', isCurrent: true });

beforeAll(async () => { replicaSet = await MongoMemoryReplSet.create({ replSet: { count: 1 } }); await mongoose.connect(replicaSet.getUri()); await Promise.all([Document.init(), FileUploadSession.init(), StorageReservation.init(), UserStorageUsage.init()]); });
beforeEach(async () => Promise.all([Document.deleteMany({}), FileUploadSession.deleteMany({}), StorageReservation.deleteMany({}), UserStorageUsage.deleteMany({})]));
afterAll(async () => { await mongoose.disconnect(); await replicaSet.stop(); });

describe('document persistence indexes', () => {
  it('enforces singleton, idempotency, reservation, usage, expiry, and verification indexes at MongoDB level', async () => { const owner = objectId(); for (const input of [{ owner, category: 'resume', entityType: 'candidate-profile' }, { owner, category: 'profile-photo', entityType: 'candidate-profile' }, { owner, category: 'profile-photo', entityType: 'recruiter-profile' }]) { const entityId = objectId(); await Document.create(documentData({ ...input, entityId })); await expect(Document.create(documentData({ ...input, entityId }))).rejects.toMatchObject({ code: 11000 }); } const company = objectId(); const companyEntity = objectId(); await Document.create(documentData({ owner, company, category: 'company-logo', entityType: 'company', entityId: companyEntity })); await expect(Document.create(documentData({ owner: objectId(), company, category: 'company-logo', entityType: 'company', entityId: companyEntity }))).rejects.toMatchObject({ code: 11000 }); const uploadSession = objectId(); await StorageReservation.create({ user: owner, uploadSession, bytes: 10, expiresAt: new Date(Date.now() + 60000) }); await expect(StorageReservation.create({ user: owner, uploadSession, bytes: 10, expiresAt: new Date(Date.now() + 60000) })).rejects.toMatchObject({ code: 11000 }); await UserStorageUsage.create({ user: owner }); await expect(UserStorageUsage.create({ user: owner })).rejects.toMatchObject({ code: 11000 }); const key = `index:${objectId()}`; const sessionData = { createdBy: owner, owner, category: 'resume', entityType: 'user', entityId: owner, purpose: 'index', expectedMimeTypes: ['application/pdf'], maximumBytes: 10, idempotencyKey: key, expiresAt: new Date(Date.now() + 60000) }; await FileUploadSession.create(sessionData); await expect(FileUploadSession.create(sessionData)).rejects.toMatchObject({ code: 11000 }); const documentIndexes = await Document.collection.indexes(); expect(documentIndexes.map(({ name }) => name)).toEqual(expect.arrayContaining(['one_current_owner_document', 'one_current_company_document', 'verification.status_1', 'entityType_1_entityId_1'])); const reservationIndexes = await StorageReservation.collection.indexes(); expect(reservationIndexes.some(({ key }) => key.status === 1 && key.expiresAt === 1)).toBe(true); expect(reservationIndexes.some(({ unique, key: indexKey }) => unique && indexKey.uploadSession === 1)).toBe(true); });
});
