import mongoose from 'mongoose';
import { MongoMemoryReplSet } from 'mongodb-memory-server';
import request from 'supertest';
import { afterAll, beforeAll, beforeEach, describe, expect, it } from 'vitest';
import { app } from '../src/app.js';
import { CandidateProfile } from '../src/models/CandidateProfile.js';
import { Document } from '../src/models/Document.js';
import { FileUploadSession } from '../src/models/FileUploadSession.js';
import { User } from '../src/models/User.js';
import { resetMemoryStorage } from '../src/services/fileStorageProvider.service.js';

let replicaSet; let sequence = 0;
const auth = (method, path, token) => request(app)[method](path).set('Authorization', `Bearer ${token}`);
const registerCandidate = async () => { sequence += 1; const response = await request(app).post('/api/v1/auth/register').send({ fullName: `Sync Candidate ${sequence}`, email: `sync.${sequence}@talvix.test`, password: 'Strong!Pass123', role: 'candidate' }).expect(201); const user = response.body.data.user; const profile = await CandidateProfile.findOne({ user: user._id }); return { token: response.body.data.accessToken, user: { ...user, id: user._id }, profile }; };
const session = async (account, category, entityType, entityId) => (await auth('post', '/api/v1/documents/upload-session', account.token).send({ category, entityType, entityId: String(entityId), purpose: category }).expect(201)).body.data.uploadSession.id;
const attach = (path, token, uploadSessionId, bytes, fileName, mimeType) => auth('post', path, token).field('uploadSessionId', uploadSessionId).field('purpose', fileName).attach('file', bytes, { filename: fileName, contentType: mimeType });

beforeAll(async () => { replicaSet = await MongoMemoryReplSet.create({ replSet: { count: 1 } }); await mongoose.connect(replicaSet.getUri()); await Promise.all([User.init(), CandidateProfile.init(), Document.init(), FileUploadSession.init()]); });
beforeEach(async () => { await Promise.all([User.deleteMany({}), CandidateProfile.deleteMany({}), Document.deleteMany({}), FileUploadSession.deleteMany({})]); resetMemoryStorage(); });
afterAll(async () => { await mongoose.disconnect(); await replicaSet.stop(); });

describe('profile document synchronization', () => {
  it('synchronizes and versions a candidate resume without changing another profile', async () => { const account = await registerCandidate(); const other = await registerCandidate(); const firstSession = await session(account, 'resume', 'candidate-profile', account.profile.id); const first = await attach('/api/v1/documents/me/resume', account.token, firstSession, Buffer.from('%PDF-1.4\nFirst'), 'resume.pdf', 'application/pdf').expect(201); const firstId = first.body.data.document.id; expect((await CandidateProfile.findById(account.profile.id)).resumeDocument.toString()).toBe(firstId); await auth('get', '/api/v1/documents/me/resume', other.token).expect(404); const secondSession = await session(account, 'resume', 'candidate-profile', account.profile.id); const second = await attach('/api/v1/documents/me/resume/replace', account.token, secondSession, Buffer.from('%PDF-1.4\nSecond'), 'resume.pdf', 'application/pdf').expect(201); expect(second.body.data.document.version).toBe(2); expect((await Document.findById(firstId)).status).toBe('replaced'); expect((await CandidateProfile.findById(account.profile.id)).resumeDocument.toString()).toBe(second.body.data.document.id); });
  it('allows only one winner during concurrent resume replacement', async () => { const account = await registerCandidate(); const initialSession = await session(account, 'resume', 'candidate-profile', account.profile.id); await attach('/api/v1/documents/me/resume', account.token, initialSession, Buffer.from('%PDF-1.4\nInitial'), 'resume.pdf', 'application/pdf').expect(201); const [one, two] = await Promise.all([session(account, 'resume', 'candidate-profile', account.profile.id), session(account, 'resume', 'candidate-profile', account.profile.id)]); const results = await Promise.all([attach('/api/v1/documents/me/resume/replace', account.token, one, Buffer.from('%PDF-1.4\nOne'), 'one.pdf', 'application/pdf'), attach('/api/v1/documents/me/resume/replace', account.token, two, Buffer.from('%PDF-1.4\nTwo'), 'two.pdf', 'application/pdf')]); expect(results.map((result) => result.status).sort()).toEqual([201, 409]); const current = await Document.find({ owner: account.user.id, category: 'resume', status: 'active', isCurrent: true }); expect(current).toHaveLength(1); expect((await CandidateProfile.findById(account.profile.id)).resumeDocument.toString()).toBe(current[0].id); });
  it('synchronizes candidate profile-photo replacement and deletion', async () => { const account = await registerCandidate(); const firstSession = await session(account, 'profile-photo', 'candidate-profile', account.profile.id); const png = Buffer.from([0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a,1]); await attach('/api/v1/documents/me/profile-photo', account.token, firstSession, png, 'photo.png', 'image/png').expect(201); expect((await CandidateProfile.findById(account.profile.id)).profilePhotoDocument).not.toBeNull(); const replacementSession = await session(account, 'profile-photo', 'candidate-profile', account.profile.id); await attach('/api/v1/documents/me/profile-photo/replace', account.token, replacementSession, Buffer.concat([png, Buffer.from([2])]), 'photo.png', 'image/png').expect(201); await auth('delete', '/api/v1/documents/me/profile-photo', account.token).expect(200); expect((await CandidateProfile.findById(account.profile.id)).profilePhotoDocument).toBeNull(); });
});
