import { beforeEach, describe, expect, it, vi } from 'vitest';

const state = vi.hoisted(() => ({ options: null, buffer: null, destroy: vi.fn(), resource: vi.fn(), signed: vi.fn(), uploadError: null }));
vi.mock('../src/config/env.js', () => ({ env: { FILE_UPLOADS_ENABLED: true, FILE_STORAGE_PROVIDER: 'cloudinary', CLOUDINARY_CLOUD_NAME: 'test-cloud', CLOUDINARY_API_KEY: 'test-key', CLOUDINARY_API_SECRET: 'never-expose-this-secret', FILE_SIGNED_URL_TTL_SECONDS: 300 } }));
vi.mock('cloudinary', () => ({ v2: { config: vi.fn(), uploader: { upload_stream: vi.fn((options, callback) => { state.options = options; return { end: (buffer) => { state.buffer = buffer; if (state.uploadError) callback(state.uploadError); else callback(null, { public_id: `${options.folder}/normalized_id`, resource_type: options.resource_type, format: options.resource_type === 'image' ? 'png' : 'pdf', bytes: buffer.length, secure_url: 'https://private.invalid/asset', version: 2, etag: 'etag', created_at: '2026-01-01T00:00:00.000Z' }); } }; }), destroy: state.destroy }, api: { resource: state.resource }, utils: { private_download_url: state.signed } } }));

const provider = await import('../src/services/fileStorageProvider.service.js');
const folder = 'talvix/candidate/507f1f77bcf86cd799439011';
beforeEach(() => { state.options = null; state.buffer = null; state.uploadError = null; state.destroy.mockReset().mockResolvedValue({ result: 'ok' }); state.resource.mockReset().mockResolvedValue({ bytes: 10 }); state.signed.mockReset().mockReturnValue('https://signed.invalid/file'); });

describe('Cloudinary storage adapter', () => {
  it.each([['image', 'photo.png'], ['raw', 'resume.pdf']])('uploads %s files through authenticated storage', async (resourceType, fileName) => { const buffer = Buffer.from('private bytes'); const result = await provider.uploadFile({ buffer, fileName, mimeType: 'application/octet-stream', folder, resourceType, accessMode: 'private', metadata: { category: 'resume' } }); expect(state.options).toMatchObject({ folder, resource_type: resourceType, type: 'authenticated', use_filename: false, overwrite: false }); expect(state.buffer).toBe(buffer); expect(result).toMatchObject({ provider: 'cloudinary', publicId: `${folder}/normalized_id`, resourceType, bytes: buffer.length }); expect(result).not.toHaveProperty('api_secret'); });
  it('rejects client-controlled folders and traversal identifiers', async () => { await expect(provider.uploadFile({ buffer: Buffer.from('x'), fileName: 'x.pdf', folder: '../client', resourceType: 'raw' })).rejects.toMatchObject({ message: 'File storage upload failed' }); await expect(provider.deleteFile({ publicId: `${folder}/../secret` })).rejects.toMatchObject({ message: 'Invalid stored file identifier' }); });
  it('sanitizes provider failures without leaking secrets or buffers', async () => { state.uploadError = new Error('never-expose-this-secret private bytes'); await expect(provider.uploadFile({ buffer: Buffer.from('private bytes'), fileName: 'x.pdf', folder, resourceType: 'raw' })).rejects.toMatchObject({ message: 'File storage upload failed' }); state.destroy.mockRejectedValue(new Error('never-expose-this-secret')); await expect(provider.deleteFile({ publicId: `${folder}/safe_id` })).rejects.toMatchObject({ message: 'Stored file deletion failed' }); });
  it('uses authenticated bounded signed URLs and metadata lookup', async () => { const requested = new Date(Date.now() + 3600000); const download = await provider.createSignedDownloadUrl({ publicId: `${folder}/safe_id`, resourceType: 'raw', expiresAt: requested, attachment: true }); expect(state.signed).toHaveBeenCalledWith(`${folder}/safe_id`, '', expect.objectContaining({ type: 'authenticated', resource_type: 'raw', attachment: true })); expect(download.expiresAt.getTime()).toBeLessThan(requested.getTime()); await provider.getFileMetadata({ publicId: `${folder}/safe_id`, resourceType: 'raw' }); expect(state.resource).toHaveBeenCalledWith(`${folder}/safe_id`, { resource_type: 'raw', type: 'authenticated' }); });
});
