import mongoose from 'mongoose';
import { MongoMemoryReplSet } from 'mongodb-memory-server';
import request from 'supertest';
import { afterAll, beforeAll, beforeEach, describe, expect, it } from 'vitest';
import { app } from '../src/app.js';
import { Company } from '../src/models/Company.js';
import { Document } from '../src/models/Document.js';
import { FileUploadSession } from '../src/models/FileUploadSession.js';
import { InterviewProcess } from '../src/models/InterviewProcess.js';
import { RecruiterProfile } from '../src/models/RecruiterProfile.js';
import { StorageReservation } from '../src/models/StorageReservation.js';
import { User } from '../src/models/User.js';
import { UserStorageUsage } from '../src/models/UserStorageUsage.js';
import { resetMemoryStorage } from '../src/services/fileStorageProvider.service.js';

let replicaSet; let sequence = 0;
const api = (method, path, token) => request(app)[method](path).set('Authorization', `Bearer ${token}`);
const register = async (role) => { sequence += 1; const response = await request(app).post('/api/v1/auth/register').send({ fullName: `${role} Interview Doc ${sequence}`, email: `interview.doc.${sequence}@talvix.test`, password: 'Strong!Pass123', role }).expect(201); return { token: response.body.data.accessToken, user: response.body.data.user }; };
const recruiter = async (permissions = ['documents.manage', 'documents.view', 'interviews.manage', 'interviews.view'], options = {}) => { const actor = await register('recruiter'); const company = await Company.create({ name: `Interview Document Co ${sequence}`, slug: `interview-document-${sequence}`, owner: actor.user._id, verificationStatus: options.verificationStatus ?? 'verified', isActive: options.companyActive ?? true, teamMembers: [{ recruiter: actor.user._id, permissions, status: options.membershipStatus ?? 'active' }] }); await RecruiterProfile.updateOne({ user: actor.user._id }, { company: company.id, isApproved: options.approved ?? true, permissions }); return { ...actor, company }; };
const processFor = (actor, candidate, status = 'active') => InterviewProcess.create({ application: new mongoose.Types.ObjectId(), candidate: candidate.user._id, job: new mongoose.Types.ObjectId(), company: actor.company.id, createdBy: actor.user._id, templateSnapshot: {}, status });
const session = async (actor, process) => (await api('post', '/api/v1/documents/upload-session', actor.token).send({ category: 'interview-attachment', entityType: 'interview-process', entityId: process.id, purpose: 'Interview evidence' }).expect(201)).body.data.uploadSession.id;
const upload = (actor, process, sessionId, access = 'company-private', purpose = 'Interview evidence') => api('post', `/api/v1/documents/manage/interviews/${process.id}`, actor.token).field('uploadSessionId', sessionId).field('purpose', purpose).field('access', access).attach('file', Buffer.from(`%PDF-1.4\nInterview ${sessionId}`), { filename: 'interview.pdf', contentType: 'application/pdf' });
const replace = (actor, process, documentId, sessionId, access) => { const builder = api('post', `/api/v1/documents/manage/interviews/${process.id}/${documentId}/replace`, actor.token).field('uploadSessionId', sessionId).field('purpose', 'Replacement evidence'); if (access) builder.field('access', access); return builder.attach('file', Buffer.from(`%PDF-1.4\nReplacement ${sessionId}`), { filename: 'replacement.pdf', contentType: 'application/pdf' }); };

beforeAll(async () => { replicaSet = await MongoMemoryReplSet.create({ replSet: { count: 1 } }); await mongoose.connect(replicaSet.getUri()); await Promise.all([User.init(), RecruiterProfile.init(), Company.init(), InterviewProcess.init(), Document.init(), FileUploadSession.init(), StorageReservation.init(), UserStorageUsage.init()]); });
beforeEach(async () => { await Promise.all([User.deleteMany({}), RecruiterProfile.deleteMany({}), Company.deleteMany({}), InterviewProcess.deleteMany({}), Document.deleteMany({}), FileUploadSession.deleteMany({}), StorageReservation.deleteMany({}), UserStorageUsage.deleteMany({})]); resetMemoryStorage(); });
afterAll(async () => { await mongoose.disconnect(); await replicaSet.stop(); });

describe('interview attachments', () => {
  it('enforces recruiter approval, membership, company status, permissions, and company scope', async () => { const candidate = await register('candidate'); const owner = await recruiter(); const process = await processFor(owner, candidate); const uploadId = await session(owner, process); await upload(owner, process, uploadId).expect(201); for (const options of [{ permissions: ['interviews.manage'] }, { membershipStatus: 'removed' }, { approved: false }, { verificationStatus: 'pending' }, { companyActive: false }]) { const denied = await recruiter(options.permissions, options); const deniedSession = await session(denied, process); await upload(denied, process, deniedSession).expect(403); } const outsider = await recruiter(); const outsiderSession = await session(outsider, process); await upload(outsider, process, outsiderSession).expect(404); await api('get', `/api/v1/documents/manage/interviews/${new mongoose.Types.ObjectId()}`, owner.token).expect(404); });
  it('separates company-private and candidate-visible documents with safe bounded downloads', async () => { const candidate = await register('candidate'); const unrelated = await register('candidate'); const owner = await recruiter(); const process = await processFor(owner, candidate); const privateSession = await session(owner, process); const privateUpload = await upload(owner, process, privateSession).expect(201); const visibleSession = await session(owner, process); const visibleUpload = await upload(owner, process, visibleSession, 'candidate-visible').expect(201); expect(JSON.stringify(visibleUpload.body)).not.toMatch(/publicId|secureUrl|memory:\/\//); const candidateList = await api('get', `/api/v1/documents/interviews/${process.id}`, candidate.token).expect(200); expect(candidateList.body.data.documents).toHaveLength(1); expect(candidateList.body.data.documents[0].id).toBe(visibleUpload.body.data.document.id); await api('get', `/api/v1/documents/interviews/${process.id}`, unrelated.token).expect(404); await api('get', `/api/v1/documents/interviews/${process.id}/${privateUpload.body.data.document.id}/download`, candidate.token).expect(404); const download = await api('get', `/api/v1/documents/interviews/${process.id}/${visibleUpload.body.data.document.id}/download`, candidate.token).expect(200); expect(new Date(download.body.data.expiresAt).getTime()).toBeLessThanOrEqual(Date.now() + 301000); expect(download.body.data.url).not.toContain('memory://'); const recruiterDownload = await api('get', `/api/v1/documents/manage/interviews/${process.id}/${privateUpload.body.data.document.id}/download`, owner.token).expect(200); expect(recruiterDownload.body.data.url).toContain('files.talvix.test'); });
  it('validates access and sensitive metadata and blocks archived or quarantined downloads', async () => { const candidate = await register('candidate'); const owner = await recruiter(); const denied = await recruiter(['documents.view', 'interviews.view']); const process = await processFor(owner, candidate); const badSession = await session(owner, process); await upload(owner, process, badSession, 'public').expect(400); for (const purpose of ['meeting password=secret', 'access token abc', 'API credential']) { const sensitiveSession = await session(owner, process); await upload(owner, process, sensitiveSession, 'company-private', purpose).expect(400); } const goodSession = await session(owner, process); const uploaded = await upload(owner, process, goodSession).expect(201); const id = uploaded.body.data.document.id; await api('patch', `/api/v1/documents/manage/interviews/${process.id}/${id}/access`, denied.token).send({ access: 'candidate-visible' }).expect(403); await api('patch', `/api/v1/documents/manage/interviews/${process.id}/${id}/access`, owner.token).send({ access: 'candidate-visible' }).expect(200); await Document.updateOne({ _id: id }, { status: 'quarantined', 'malwareScan.status': 'suspicious' }); await api('get', `/api/v1/documents/manage/interviews/${process.id}/${id}/download`, owner.token).expect(404); });
  it('replaces an attachment transactionally while preserving scope and access', async () => { const candidate = await register('candidate'); const owner = await recruiter(); const process = await processFor(owner, candidate); const firstSession = await session(owner, process); const first = await upload(owner, process, firstSession, 'candidate-visible').expect(201); const previousId = first.body.data.document.id; const replacementSession = await session(owner, process); const response = await replace(owner, process, previousId, replacementSession).expect(201); const successor = await Document.findById(response.body.data.document.id); const previous = await Document.findById(previousId); expect(successor.toObject()).toMatchObject({ version: 2, category: 'interview-attachment', entityType: 'interview-process', access: 'candidate-visible' }); expect(String(successor.entityId)).toBe(process.id); expect(String(successor.company)).toBe(owner.company.id); expect(String(successor.parentDocument)).toBe(previousId); expect(previous.toObject()).toMatchObject({ status: 'replaced', isCurrent: false }); expect(String(previous.replacedBy)).toBe(successor.id); expect(JSON.stringify(response.body)).not.toMatch(/publicId|secureUrl|memory:\/\//); const listed = await api('get', `/api/v1/documents/interviews/${process.id}`, candidate.token).expect(200); expect(listed.body.data.documents.map(({ id }) => id)).toEqual([successor.id]); });
  it('allows only one concurrent replacement winner and rejects invalid scope or state', async () => { const candidate = await register('candidate'); const owner = await recruiter(); const outsider = await recruiter(); const denied = await recruiter(['documents.view', 'interviews.view']); const process = await processFor(owner, candidate); const otherProcess = await processFor(owner, candidate); const initialSession = await session(owner, process); const initial = await upload(owner, process, initialSession).expect(201); const id = initial.body.data.document.id; for (const actor of [denied, outsider]) { const replacementSession = await session(actor, process); await replace(actor, process, id, replacementSession).expect(actor === denied ? 403 : 404); } const wrongProcessSession = await session(owner, otherProcess); await replace(owner, otherProcess, id, wrongProcessSession).expect(409); const sessions = await Promise.all([session(owner, process), session(owner, process)]); const results = await Promise.all(sessions.map((replacementSession) => replace(owner, process, id, replacementSession))); expect(results.map(({ status }) => status).sort()).toEqual([201, 409]); expect(await Document.countDocuments({ company: owner.company.id, entityType: 'interview-process', entityId: process.id, category: 'interview-attachment', status: 'active', isCurrent: true })).toBe(1); const reservations = await StorageReservation.find({ uploadSession: { $in: sessions } }); expect(reservations.filter(({ status }) => status === 'committed')).toHaveLength(1); expect(reservations.filter(({ status }) => status === 'released')).toHaveLength(1); const winner = await Document.findOne({ entityId: process.id, status: 'active', isCurrent: true }); const archivedSession = await session(owner, process); await Document.updateOne({ _id: winner.id }, { status: 'archived', isCurrent: false }); const archived = await replace(owner, process, winner.id, archivedSession).expect(409); expect(archived.body.details).toBe('DOCUMENT_REPLACEMENT_NOT_ALLOWED'); expect(JSON.stringify(archived.body)).not.toMatch(/publicId|storage|stack|MongoServerError/i); });
});
