import mongoose from 'mongoose';
import { MongoMemoryReplSet } from 'mongodb-memory-server';
import request from 'supertest';
import { afterAll, beforeAll, beforeEach, describe, expect, it } from 'vitest';
import { app } from '../src/app.js';
import { Company } from '../src/models/Company.js';
import { Document } from '../src/models/Document.js';
import { FileUploadSession } from '../src/models/FileUploadSession.js';
import { Offer } from '../src/models/Offer.js';
import { RecruiterProfile } from '../src/models/RecruiterProfile.js';
import { StorageReservation } from '../src/models/StorageReservation.js';
import { User } from '../src/models/User.js';
import { UserStorageUsage } from '../src/models/UserStorageUsage.js';
import { resetMemoryStorage } from '../src/services/fileStorageProvider.service.js';

let replicaSet; let sequence = 0;
const api = (method, path, token) => request(app)[method](path).set('Authorization', `Bearer ${token}`);
const register = async (role) => { sequence += 1; const response = await request(app).post('/api/v1/auth/register').send({ fullName: `${role} Offer Doc ${sequence}`, email: `offer.doc.${sequence}@talvix.test`, password: 'Strong!Pass123', role }).expect(201); return { token: response.body.data.accessToken, user: response.body.data.user }; };
const recruiter = async (permissions = ['documents.manage', 'documents.view', 'offers.manage', 'offers.view'], options = {}) => { const actor = await register('recruiter'); const company = await Company.create({ name: `Offer Document Co ${sequence}`, slug: `offer-document-${sequence}`, owner: actor.user._id, verificationStatus: options.verificationStatus ?? 'verified', isActive: options.companyActive ?? true, teamMembers: [{ recruiter: actor.user._id, permissions, status: options.membershipStatus ?? 'active' }] }); await RecruiterProfile.updateOne({ user: actor.user._id }, { company: company.id, isApproved: options.approved ?? true, permissions }); return { ...actor, company }; };
const offerFor = (actor, candidate, status = 'draft', extra = {}) => Offer.create({ offerNumber: `TVX-DOC-${sequence}-${Date.now()}-${Math.random()}`, chainId: new mongoose.Types.ObjectId(), company: actor.company.id, job: new mongoose.Types.ObjectId(), application: new mongoose.Types.ObjectId(), candidate: candidate.user._id, createdBy: actor.user._id, title: 'Engineer', employmentType: 'full-time', workMode: 'remote', compensation: { currency: 'INR', period: 'yearly', base: 100000 }, candidateSnapshot: {}, jobSnapshot: {}, status, ...extra });
const session = async (actor, offer) => (await api('post', '/api/v1/documents/upload-session', actor.token).send({ category: 'offer-document', entityType: 'offer', entityId: offer.id, purpose: 'Offer attachment' }).expect(201)).body.data.uploadSession.id;
const upload = (actor, offer, sessionId, access = 'candidate-visible', bytes = Buffer.from(`%PDF-1.4\nOffer ${sessionId}`)) => api('post', `/api/v1/documents/manage/offers/${offer.id}`, actor.token).field('uploadSessionId', sessionId).field('purpose', 'Offer attachment').field('access', access).attach('file', bytes, { filename: 'offer.pdf', contentType: 'application/pdf' });

beforeAll(async () => { replicaSet = await MongoMemoryReplSet.create({ replSet: { count: 1 } }); await mongoose.connect(replicaSet.getUri()); await Promise.all([User.init(), RecruiterProfile.init(), Company.init(), Offer.init(), Document.init(), FileUploadSession.init(), StorageReservation.init(), UserStorageUsage.init()]); });
beforeEach(async () => { await Promise.all([User.deleteMany({}), RecruiterProfile.deleteMany({}), Company.deleteMany({}), Offer.deleteMany({}), Document.deleteMany({}), FileUploadSession.deleteMany({}), StorageReservation.deleteMany({}), UserStorageUsage.deleteMany({})]); resetMemoryStorage(); });
afterAll(async () => { await mongoose.disconnect(); await replicaSet.stop(); });

describe('offer attachments', () => {
  it('requires document and offer permissions, active approval/membership, verified company, and company scope', async () => { const candidate = await register('candidate'); const owner = await recruiter(); const offer = await offerFor(owner, candidate); const uploadId = await session(owner, offer); await upload(owner, offer, uploadId).expect(201); for (const options of [{ permissions: ['offers.manage'] }, { permissions: ['documents.manage'] }, { membershipStatus: 'removed' }, { approved: false }, { verificationStatus: 'pending' }, { companyActive: false }]) { const denied = await recruiter(options.permissions, options); const deniedSession = await session(denied, offer); await upload(denied, offer, deniedSession).expect(403); } const outsider = await recruiter(); const outsiderSession = await session(outsider, offer); await upload(outsider, offer, outsiderSession).expect(404); });
  it('enforces the documented offer-state visibility policy and candidate isolation', async () => { const candidate = await register('candidate'); const other = await register('candidate'); const owner = await recruiter(); const offer = await offerFor(owner, candidate); const uploadId = await session(owner, offer); const uploaded = await upload(owner, offer, uploadId).expect(201); const id = uploaded.body.data.document.id; for (const status of ['draft', 'pending-approval', 'approved', 'rejected']) { await Offer.updateOne({ _id: offer.id }, { status, $unset: { sentAt: 1 } }); await api('get', `/api/v1/documents/offers/${offer.id}`, candidate.token).expect(404); } await Offer.updateOne({ _id: offer.id }, { status: 'withdrawn', $unset: { sentAt: 1 } }); await api('get', `/api/v1/documents/offers/${offer.id}`, candidate.token).expect(404); for (const status of ['sent', 'viewed', 'negotiation-requested', 'accepted', 'declined', 'expired', 'superseded']) { await Offer.updateOne({ _id: offer.id }, { status, sentAt: new Date() }); const listed = await api('get', `/api/v1/documents/offers/${offer.id}`, candidate.token).expect(200); expect(listed.body.data.documents).toHaveLength(1); } await Offer.updateOne({ _id: offer.id }, { status: 'withdrawn', sentAt: new Date() }); await api('get', `/api/v1/documents/offers/${offer.id}`, candidate.token).expect(200); await api('get', `/api/v1/documents/offers/${offer.id}`, other.token).expect(404); const download = await api('get', `/api/v1/documents/offers/${offer.id}/${id}/download`, candidate.token).expect(200); expect(new Date(download.body.data.expiresAt).getTime()).toBeLessThanOrEqual(Date.now() + 301000); expect(JSON.stringify(download.body)).not.toMatch(/publicId|secureUrl|memory:\/\//); });
  it('keeps internal files private, versions replacements, preserves offer state, and blocks quarantine', async () => { const candidate = await register('candidate'); const owner = await recruiter(); const offer = await offerFor(owner, candidate, 'sent', { sentAt: new Date() }); const internalSession = await session(owner, offer); await upload(owner, offer, internalSession, 'company-private').expect(201); const visibleSession = await session(owner, offer); const visible = await upload(owner, offer, visibleSession).expect(201); const originalId = visible.body.data.document.id; const replacementSession = await session(owner, offer); const replacement = await api('post', `/api/v1/documents/manage/offers/${offer.id}/${originalId}/replace`, owner.token).field('uploadSessionId', replacementSession).field('purpose', 'Offer revision attachment').field('access', 'candidate-visible').attach('file', Buffer.from('%PDF-1.4\nReplaced'), { filename: 'replaced.pdf', contentType: 'application/pdf' }).expect(201); expect(replacement.body.data.document.version).toBe(2); expect((await Document.findById(originalId)).status).toBe('replaced'); expect((await Offer.findById(offer.id)).status).toBe('sent'); const candidateList = await api('get', `/api/v1/documents/offers/${offer.id}`, candidate.token).expect(200); expect(candidateList.body.data.documents).toHaveLength(1); const replacementId = replacement.body.data.document.id; await Document.updateOne({ _id: replacementId }, { status: 'quarantined', 'malwareScan.status': 'infected' }); await api('get', `/api/v1/documents/offers/${offer.id}/${replacementId}/download`, candidate.token).expect(404); });
});
