import mongoose from 'mongoose';
import { MongoMemoryReplSet } from 'mongodb-memory-server';
import request from 'supertest';
import { afterAll, beforeAll, beforeEach, describe, expect, it } from 'vitest';
import { app } from '../src/app.js';
import { CandidateProfile } from '../src/models/CandidateProfile.js';
import { Company } from '../src/models/Company.js';
import { Document } from '../src/models/Document.js';
import { FileUploadSession } from '../src/models/FileUploadSession.js';
import { RecruiterProfile } from '../src/models/RecruiterProfile.js';
import { StorageReservation } from '../src/models/StorageReservation.js';
import { User } from '../src/models/User.js';
import { UserStorageUsage } from '../src/models/UserStorageUsage.js';
import { getFileMetadata, resetMemoryStorage } from '../src/services/fileStorageProvider.service.js';

let replicaSet; let sequence = 0;
const png = (suffix) => Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, suffix]);
const api = (method, path, token) => request(app)[method](path).set('Authorization', `Bearer ${token}`);
const register = async (role) => { sequence += 1; const response = await request(app).post('/api/v1/auth/register').send({ fullName: `${role} Singleton ${sequence}`, email: `singleton.${sequence}@talvix.test`, password: 'Strong!Pass123', role }).expect(201); return { token: response.body.data.accessToken, user: response.body.data.user }; };
const uploadSession = async (actor, category, entityType, entityId) => (await api('post', '/api/v1/documents/upload-session', actor.token).send({ category, entityType, entityId: String(entityId), purpose: category }).expect(201)).body.data.uploadSession.id;
const upload = (actor, path, sessionId, suffix) => api('post', path, actor.token).field('uploadSessionId', sessionId).field('purpose', `image-${suffix}`).attach('file', png(suffix), { filename: `image-${suffix}.png`, contentType: 'image/png' });
const recruiter = async () => { const actor = await register('recruiter'); const company = await Company.create({ name: `Singleton Company ${sequence}`, slug: `singleton-${sequence}`, owner: actor.user._id, verificationStatus: 'verified', isActive: true, teamMembers: [{ recruiter: actor.user._id, role: 'owner', permissions: ['documents.manage'], status: 'active' }] }); const profile = await RecruiterProfile.findOneAndUpdate({ user: actor.user._id }, { company: company.id, isApproved: true, isCompanyOwner: true, permissions: ['documents.manage'] }, { returnDocument: 'after' }); return { ...actor, company, profile }; };
const assertWinner = async ({ actor, category, entityType, entityId, reference }) => { const current = await Document.find({ owner: actor.user._id, category, entityType, entityId, status: 'active', isCurrent: true }); expect(current).toHaveLength(1); expect(String(reference)).toBe(current[0].id); const predecessor = await Document.findOne({ replacedBy: current[0].id }); expect(predecessor?.status).toBe('replaced'); expect(await getFileMetadata({ publicId: predecessor.storage.publicId, resourceType: predecessor.storage.resourceType })).toBeNull(); const reservations = await StorageReservation.find({ user: actor.user._id }); expect(reservations.filter((row) => row.status === 'released')).toHaveLength(1); expect(reservations.filter((row) => row.status === 'committed')).toHaveLength(2); const usage = await UserStorageUsage.findOne({ user: actor.user._id }); expect(usage.usedBytes).toBeGreaterThanOrEqual(0); expect(usage.reservedBytes).toBe(0); };

beforeAll(async () => { replicaSet = await MongoMemoryReplSet.create({ replSet: { count: 1 } }); await mongoose.connect(replicaSet.getUri()); await Promise.all([User.init(), CandidateProfile.init(), RecruiterProfile.init(), Company.init(), Document.init(), FileUploadSession.init(), StorageReservation.init(), UserStorageUsage.init()]); });
beforeEach(async () => { await Promise.all([User.deleteMany({}), CandidateProfile.deleteMany({}), RecruiterProfile.deleteMany({}), Company.deleteMany({}), Document.deleteMany({}), FileUploadSession.deleteMany({}), StorageReservation.deleteMany({}), UserStorageUsage.deleteMany({})]); resetMemoryStorage(); });
afterAll(async () => { await mongoose.disconnect(); await replicaSet.stop(); });

describe('singleton document replacement concurrency', () => {
  it('keeps exactly one candidate profile photo and cleans the losing asset and reservation', async () => { const actor = await register('candidate'); const profile = await CandidateProfile.findOne({ user: actor.user._id }); const first = await uploadSession(actor, 'profile-photo', 'candidate-profile', profile.id); await upload(actor, '/api/v1/documents/me/profile-photo', first, 1).expect(201); const sessions = await Promise.all([2, 3].map(() => uploadSession(actor, 'profile-photo', 'candidate-profile', profile.id))); const responses = await Promise.all(sessions.map((id, index) => upload(actor, '/api/v1/documents/me/profile-photo/replace', id, index + 2))); expect(responses.map(({ status }) => status).sort()).toEqual([201, 409]); expect(JSON.stringify(responses.find(({ status }) => status === 409).body)).not.toMatch(/publicId|cloudinary|storage|stack/i); const updated = await CandidateProfile.findById(profile.id); await assertWinner({ actor, category: 'profile-photo', entityType: 'candidate-profile', entityId: profile.id, reference: updated.profilePhotoDocument }); });
  it('keeps exactly one recruiter profile photo and rejects another recruiter', async () => { const actor = await recruiter(); const outsider = await recruiter(); const first = await uploadSession(actor, 'profile-photo', 'recruiter-profile', actor.profile.id); await upload(actor, '/api/v1/documents/me/recruiter-profile-photo', first, 1).expect(201); const foreignSession = await uploadSession(outsider, 'profile-photo', 'recruiter-profile', actor.profile.id); await upload(outsider, '/api/v1/documents/me/recruiter-profile-photo/replace', foreignSession, 9).expect(400); const sessions = await Promise.all([2, 3].map(() => uploadSession(actor, 'profile-photo', 'recruiter-profile', actor.profile.id))); const responses = await Promise.all(sessions.map((id, index) => upload(actor, '/api/v1/documents/me/recruiter-profile-photo/replace', id, index + 2))); expect(responses.map(({ status }) => status).sort()).toEqual([201, 409]); const updated = await RecruiterProfile.findById(actor.profile.id); await assertWinner({ actor, category: 'profile-photo', entityType: 'recruiter-profile', entityId: actor.profile.id, reference: updated.profilePhotoDocument }); });
  it('keeps exactly one company logo and prevents cross-company replacement', async () => { const actor = await recruiter(); const outsider = await recruiter(); const first = await uploadSession(actor, 'company-logo', 'company', actor.company.id); await upload(actor, '/api/v1/documents/company/logo', first, 1).expect(201); const foreignSession = await uploadSession(outsider, 'company-logo', 'company', actor.company.id); await upload(outsider, '/api/v1/documents/company/logo/replace', foreignSession, 9).expect(400); const sessions = await Promise.all([2, 3].map(() => uploadSession(actor, 'company-logo', 'company', actor.company.id))); const responses = await Promise.all(sessions.map((id, index) => upload(actor, '/api/v1/documents/company/logo/replace', id, index + 2))); expect(responses.map(({ status }) => status).sort()).toEqual([201, 409]); const updated = await Company.findById(actor.company.id); await assertWinner({ actor, category: 'company-logo', entityType: 'company', entityId: actor.company.id, reference: updated.logoDocument }); });
});
