import mongoose from 'mongoose';
import { MongoMemoryReplSet } from 'mongodb-memory-server';
import { afterAll, beforeAll, beforeEach, describe, expect, it } from 'vitest';
import { Document } from '../src/models/Document.js';
import { StorageReservation } from '../src/models/StorageReservation.js';
import { UserStorageUsage } from '../src/models/UserStorageUsage.js';
import { commitStorageReservation, expireStaleReservations, recalculateUserStorageUsage, releaseStorageReservation, reserveStorage } from '../src/services/storageReservation.service.js';

let replicaSet;
const megabytes = (value) => value * 1024 * 1024;
const reservationInput = (user, bytes, expiresAt = new Date(Date.now() + 60000)) => ({ user, uploadSession: new mongoose.Types.ObjectId(), bytes, expiresAt });

beforeAll(async () => { replicaSet = await MongoMemoryReplSet.create({ replSet: { count: 1 } }); await mongoose.connect(replicaSet.getUri()); await Promise.all([Document.init(), UserStorageUsage.init(), StorageReservation.init()]); });
beforeEach(async () => { await Promise.all([Document.deleteMany({}), UserStorageUsage.deleteMany({}), StorageReservation.deleteMany({})]); });
afterAll(async () => { await mongoose.disconnect(); await replicaSet.stop(); });

describe('distributed storage reservations', () => {
  it('reserves, commits, and releases counters idempotently', async () => { const user = new mongoose.Types.ObjectId(); const first = await reserveStorage(reservationInput(user, 1024)); let usage = await UserStorageUsage.findOne({ user }); expect(usage.reservedBytes).toBe(1024); await commitStorageReservation(first.id); usage = await UserStorageUsage.findOne({ user }); expect(usage.toObject()).toMatchObject({ usedBytes: 1024, reservedBytes: 0, documentCount: 1 }); await commitStorageReservation(first.id); const second = await reserveStorage(reservationInput(user, 2048)); await releaseStorageReservation(second.id); await releaseStorageReservation(second.id); usage = await UserStorageUsage.findOne({ user }); expect(usage.reservedBytes).toBe(0); expect(usage.usedBytes).toBe(1024); });
  it('atomically prevents concurrent quota overrun across independent calls', async () => { const user = new mongoose.Types.ObjectId(); const results = await Promise.allSettled([reserveStorage(reservationInput(user, megabytes(60))), reserveStorage(reservationInput(user, megabytes(60)))]); expect(results.filter((result) => result.status === 'fulfilled')).toHaveLength(1); expect(results.filter((result) => result.status === 'rejected')).toHaveLength(1); const usage = await UserStorageUsage.findOne({ user }); expect(usage.reservedBytes).toBe(megabytes(60)); expect(usage.usedBytes + usage.reservedBytes).toBeLessThanOrEqual(megabytes(100)); });
  it('expires stale reservations, cannot commit them, and never expires committed reservations', async () => { const user = new mongoose.Types.ObjectId(); const reservation = await reserveStorage(reservationInput(user, 4096, new Date(Date.now() - 1000))); expect(await expireStaleReservations()).toBe(1); await expect(commitStorageReservation(reservation.id)).rejects.toMatchObject({ details: 'STORAGE_RESERVATION_EXPIRED' }); await releaseStorageReservation(reservation.id); const committed = await reserveStorage(reservationInput(user, 2048)); await commitStorageReservation(committed.id); expect(await expireStaleReservations(new Date(Date.now() + 86400000))).toBe(0); const usage = await UserStorageUsage.findOne({ user }); expect(usage.reservedBytes).toBe(0); expect(usage.usedBytes).toBeGreaterThanOrEqual(0); });
  it('reconciles inflated, understated, reserved, and document counters from retained state', async () => { const user = new mongoose.Types.ObjectId(); await UserStorageUsage.create({ user, usedBytes: 999999, reservedBytes: 8888, documentCount: 99 }); await Document.create({ owner: user, ownerRole: 'candidate', uploadedBy: user, category: 'resume', purpose: 'Retained resume', entityType: 'candidate-profile', entityId: new mongoose.Types.ObjectId(), originalFileName: 'resume.pdf', displayName: 'Resume', extension: 'pdf', mimeType: 'application/pdf', mediaType: 'document', sizeBytes: 1234, checksum: 'a'.repeat(64), storage: { provider: 'memory', publicId: `talvix/candidate/${user}/retained`, resourceType: 'raw' }, access: 'private', status: 'archived', isCurrent: false }); let usage = await recalculateUserStorageUsage(user); expect(usage.toObject()).toMatchObject({ usedBytes: 1234, reservedBytes: 0, documentCount: 1 }); await UserStorageUsage.updateOne({ user }, { usedBytes: 1, documentCount: 0 }); usage = await recalculateUserStorageUsage(user); expect(usage.toObject()).toMatchObject({ usedBytes: 1234, documentCount: 1 }); });
});
