import mongoose from 'mongoose';
import { ATTEMPT_STATUSES, SUBMISSION_REASONS } from '../constants/assessment.js';
const answerSchema = new mongoose.Schema({ questionId: { type: mongoose.Schema.Types.ObjectId, required: true }, questionType: { type: String, required: true }, answer: mongoose.Schema.Types.Mixed, code: String, language: String, savedAt: Date, timeSpentSeconds: { type: Number, min: 0, default: 0 }, flaggedForReview: { type: Boolean, default: false } }, { _id: false });
const resultSchema = new mongoose.Schema({ questionId: { type: mongoose.Schema.Types.ObjectId, required: true }, questionType: String, marks: Number, awardedMarks: Number, isCorrect: Boolean, requiresManualReview: Boolean, feedback: { type: String, maxlength: 3000, default: '' }, codingResult: mongoose.Schema.Types.Mixed }, { _id: false });
const attemptSchema = new mongoose.Schema({
  assignment: { type: mongoose.Schema.Types.ObjectId, ref: 'AssessmentAssignment', required: true, index: true }, assessment: { type: mongoose.Schema.Types.ObjectId, ref: 'Assessment', required: true }, application: { type: mongoose.Schema.Types.ObjectId, ref: 'Application', required: true }, candidate: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true, index: true }, company: { type: mongoose.Schema.Types.ObjectId, ref: 'Company', required: true, index: true }, attemptNumber: { type: Number, required: true, min: 1 }, status: { type: String, enum: ATTEMPT_STATUSES, default: 'not-started' }, startedAt: Date, expiresAt: Date, submittedAt: Date, completedAt: Date, questionOrder: [{ type: mongoose.Schema.Types.ObjectId }], optionOrders: { type: mongoose.Schema.Types.Mixed, default: {} }, answers: { type: [answerSchema], default: [] }, evaluation: { objectiveScore: { type: Number, default: 0 }, subjectiveScore: { type: Number, default: 0 }, codingScore: { type: Number, default: 0 }, negativeMarks: { type: Number, default: 0 }, totalScore: { type: Number, default: 0 }, percentage: { type: Number, default: 0 }, passed: { type: Boolean, default: false }, evaluatedAt: Date, reviewedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' }, reviewedAt: Date }, questionResults: { type: [resultSchema], default: [] }, submissionReason: { type: String, enum: SUBMISSION_REASONS }, integrity: { startIp: String, lastIp: String, userAgent: String, saveCount: { type: Number, default: 0 }, suspiciousEvents: { type: [new mongoose.Schema({ type: String, detail: String, at: { type: Date, default: Date.now } }, { _id: false })], default: [] } }, audit: { type: [new mongoose.Schema({ action: String, reason: String, actor: mongoose.Schema.Types.ObjectId, at: { type: Date, default: Date.now } }, { _id: true })], default: [] },
}, { timestamps: true, versionKey: false });
attemptSchema.index({ assignment: 1, attemptNumber: 1 }, { unique: true }); attemptSchema.index({ assignment: 1, status: 1 }, { unique: true, partialFilterExpression: { status: 'in-progress' } }); attemptSchema.index({ candidate: 1, createdAt: -1 }); attemptSchema.index({ company: 1, status: 1 });
export const AssessmentAttempt = mongoose.model('AssessmentAttempt', attemptSchema);
