import mongoose from 'mongoose';
import { ASSESSMENT_STATUSES, ASSESSMENT_TYPES } from '../constants/assessment.js';
const assessmentQuestionSchema = new mongoose.Schema({ question: { type: mongoose.Schema.Types.ObjectId, ref: 'Question', required: true }, marks: { type: Number, required: true, min: 0.01 }, order: { type: Number, required: true, min: 0 }, isRequired: { type: Boolean, default: true } }, { _id: false });
const attachmentSchema = new mongoose.Schema({ enabled: { type: Boolean, default: false }, maximumFiles: { type: Number, min: 0, max: 10, default: 0 }, maximumFileBytes: { type: Number, min: 1024, max: 100 * 1024 * 1024, default: 10 * 1024 * 1024 }, maximumTotalBytes: { type: Number, min: 1024, max: 200 * 1024 * 1024, default: 20 * 1024 * 1024 }, allowedMimeTypes: { type: [String], default: [] } }, { _id: false });
const assessmentSchema = new mongoose.Schema({
  company: { type: mongoose.Schema.Types.ObjectId, ref: 'Company', required: true, index: true }, createdBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true }, title: { type: String, required: true, maxlength: 200 }, description: { type: String, maxlength: 3000, default: '' }, instructions: { type: String, maxlength: 5000, default: '' }, type: { type: String, enum: ASSESSMENT_TYPES, required: true }, skills: { type: [String], default: [] }, durationMinutes: { type: Number, required: true, min: 5, max: 300 }, totalMarks: { type: Number, min: 0, default: 0 }, passingPercentage: { type: Number, min: 0, max: 100, required: true }, maximumAttempts: { type: Number, min: 1, max: 5, default: 1 }, shuffleQuestions: { type: Boolean, default: false }, shuffleOptions: { type: Boolean, default: false }, showResultImmediately: { type: Boolean, default: false }, allowBackNavigation: { type: Boolean, default: true }, negativeMarking: { type: Boolean, default: false }, negativeMarkValue: { type: Number, min: 0, default: 0 }, attachments: { type: attachmentSchema, default: () => ({}) }, status: { type: String, enum: ASSESSMENT_STATUSES, default: 'draft' }, questions: { type: [assessmentQuestionSchema], default: [] }, version: { type: Number, min: 1, default: 1 }, publishedAt: Date, archivedAt: Date,
}, { timestamps: true, versionKey: false });
assessmentSchema.index({ company: 1, status: 1 }); assessmentSchema.index({ company: 1, createdBy: 1 }); assessmentSchema.index({ title: 'text' }); assessmentSchema.index({ skills: 1 }); assessmentSchema.index({ createdAt: -1 }); assessmentSchema.index({ archivedAt: 1 });
export const Assessment = mongoose.model('Assessment', assessmentSchema);
