import mongoose from 'mongoose';

const backgroundJobSchema = new mongoose.Schema(
  {
    type: {
      type: String,
      required: true,
      enum: [
        'SEND_EMAIL',
        'RETENTION_CLEANUP',
        'EXPIRE_INVITATION',
        'EXPIRE_JOIN_REQUEST',
        'REVOKE_SESSION',
        'GENERATE_AUDIT_REPORT',
        'EXPIRE_JOBS',
        'PUBLISH_JOBS',
        'REMIND_FEEDBACK_PENDING',
        'SYNC_CALENDAR',
        'CLEANUP_EXPIRED_MEETINGS',
        'EXPIRE_OFFERS',
        'EVALUATE_SUBMISSION',
        'AI_ASSESSMENT_EVALUATION',
        'PUBLISH_ASSESSMENT_RESULTS',
        'ASSESSMENT_REMINDER',
        'CLEANUP_ASSESSMENT_DATA',
        'PLAGIARISM_ANALYSIS',
        'GENERATE_RESULT_REPORT',
        'AI_REQUEST',
        'AI_USAGE_AGGREGATION',
        'AI_CACHE_CLEANUP',
        'RESUME_PARSE',
        'JOB_PARSE',
        'OCR_PROCESS',
        'EMBEDDING_GENERATION',
        'RESUME_REINDEX',
        'JOB_REINDEX',
        'RESUME_EMBEDDING',
        'EMBEDDING_REBUILD',
        'EMBEDDING_CLEANUP',
        'JOB_EMBEDDING',
        'JOB_EMBEDDING_REBUILD',
        'AI_COPILOT',
        'AI_SEARCH',
        'AI_SUMMARIZATION',
        'AI_COMPARISON',
        'AI_RECOMMENDATION',
        'AI_REPORT',
        'AI_EXPORT',
        'ASSESSMENT_GENERATION',
        'INTERVIEW_GENERATION',
        'QUESTION_GENERATION',
        'QUESTION_VALIDATION',
        'QUESTION_REVIEW',
        'ANSWER_EVALUATION',
        'CODE_ANALYSIS',
        'ASSESSMENT_ANALYTICS',
        'ASSESSMENT_EXPORT',
        'INTERVIEW_REPORT',
        'RESUME_REVIEW',
        'CAREER_ANALYSIS',
        'SKILL_GAP_ANALYSIS',
        'FRAUD_DETECTION',
        'DUPLICATE_RESUME_SCAN',
        'AI_RESUME_DETECTION',
        'SALARY_PREDICTION',
        'CANDIDATE_INTELLIGENCE',
        'EXECUTIVE_ANALYTICS',
        'MESSAGE_DELIVERY',
        'MESSAGE_INDEXING',
        'EMAIL_NOTIFICATION',
        'PUSH_NOTIFICATION',
        'INTERVIEW_REMINDER',
        'DAILY_DIGEST',
        'CHAT_SUMMARY',
        'FILE_SCAN',
        'FILE_CLEANUP',
        'NOTIFICATION_CLEANUP',
        'WORKFORCE_ANALYTICS',
        'RECRUITER_ANALYTICS',
        'CANDIDATE_ANALYTICS',
        'AI_USAGE_ANALYTICS',
        'MONTHLY_REPORT',
        'WEEKLY_REPORT',
        'PREDICTIVE_ANALYTICS',
        'DASHBOARD_REFRESH',
        'WORKFLOW_EXECUTION',
        'WORKFLOW_RETRY',
        'WORKFLOW_SCHEDULER',
        'WORKFLOW_CLEANUP',
        'AGENT_EXECUTION',
        'EMAIL_AUTOMATION',
        'INTERVIEW_AUTOMATION',
        'REPORT_AUTOMATION',
        'NOTIFICATION_AUTOMATION',
        'HRIS_SYNC',
        'WEBHOOK_DISPATCH',
        'INTEGRATION_HEALTH_CHECK',
        'SECURITY_SCAN',
        'AUDIT_ARCHIVE',
        'SECRET_ROTATION',
        'COMPLIANCE_AUDIT',
        'SESSION_CLEANUP',
        'NOTIFICATION_DISPATCH',
        'USAGE_AGGREGATION',
        'LICENSE_SYNC',
        'SCIM_SYNC',
        'TENANT_HEALTH_CHECK'
      ],
      index: true,
    },
    priority: {
      type: String,
      enum: ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'],
      default: 'MEDIUM',
      required: true,
      index: true,
    },
    priorityWeight: {
      type: Number,
      default: 2, // MEDIUM: 2, LOW: 1, HIGH: 3, CRITICAL: 4
      required: true,
      index: true,
    },
    status: {
      type: String,
      enum: ['pending', 'processing', 'completed', 'failed'],
      default: 'pending',
      required: true,
      index: true,
    },
    payload: {
      type: mongoose.Schema.Types.Mixed,
      default: () => ({}),
    },
    attempts: {
      type: Number,
      default: 0,
      required: true,
    },
    maxAttempts: {
      type: Number,
      default: 3,
      required: true,
    },
    runAt: {
      type: Date,
      default: Date.now,
      required: true,
      index: true,
    },
    processedAt: {
      type: Date,
      default: null,
    },
    failedAt: {
      type: Date,
      default: null,
    },
    lastError: {
      type: String,
      default: '',
    },
    lockedAt: {
      type: Date,
      default: null,
      index: true,
    },
    lockedBy: {
      type: String,
      default: null,
      index: true,
    },
  },
  {
    timestamps: true,
    versionKey: false,
  }
);

// Map priorities to weights for database-level sorting
backgroundJobSchema.pre('save', function (next) {
  const weights = { LOW: 1, MEDIUM: 2, HIGH: 3, CRITICAL: 4 };
  this.priorityWeight = weights[this.priority] || 2;
  if (typeof next === 'function') {
    next();
  }
});

export const BackgroundJob = mongoose.model('BackgroundJob', backgroundJobSchema);
