import { DOMAIN_EVENTS } from '../constants/domainEvents.js';
import { Document } from '../models/Document.js';
import { AppError } from '../shared/errors/AppError.js';
import { buildPagination } from '../utils/pagination.js';
import { serializeAdminDocument } from '../utils/documentSerializer.js';
import { publishOptionalDomainEvent } from './domainEvent.service.js';

const get = async (id) => { const document = await Document.findById(id); if (!document) throw new AppError('Document not found', 404); return document; };
const publishQuarantine = (document) => publishOptionalDomainEvent({ type: DOMAIN_EVENTS.DOCUMENT_QUARANTINED, recipientIds: [String(document.owner)], payload: { documentId: String(document.id), category: document.category, displayName: document.displayName, status: document.malwareScan.status === 'infected' ? 'infected' : document.malwareScan.status === 'suspicious' ? 'suspicious' : 'quarantined', actionUrl: '/candidate/documents' }, deduplicationKey: `document.quarantined:${document.id}:${document.malwareScan.status}:${document.statusHistory.length}` });
export const list = async (query) => { const filter = {}; if (query.category) filter.category = query.category; if (query.status) filter.status = query.status; const [rows, total] = await Promise.all([Document.find(filter).sort({ createdAt: -1 }).skip((query.page - 1) * query.limit).limit(query.limit), Document.countDocuments(filter)]); return { documents: rows.map(serializeAdminDocument), pagination: buildPagination(query.page, query.limit, total) }; };
export const inspect = async (id) => serializeAdminDocument(await get(id));
export const transition = async (id, actor, status, reason) => { const document = await get(id); if (document.status === status) return serializeAdminDocument(document); const from = document.status; document.status = status; document.isCurrent = status === 'active'; if (status === 'quarantined' && !['suspicious', 'infected'].includes(document.malwareScan.status)) document.malwareScan.status = 'pending'; document.statusHistory.push({ from, to: status, changedBy: actor, reason, adminOverride: true }); await document.save(); if (status === 'quarantined') await publishQuarantine(document); return serializeAdminDocument(document); };
export const scan = async (id, actor, status, reason) => { const document = await get(id); const previous = document.status; const unchanged = document.malwareScan.status === status && document.status === (['suspicious', 'infected'].includes(status) ? 'quarantined' : document.status); document.malwareScan = { status, provider: 'admin-metadata', scannedAt: new Date(), result: reason }; if (['suspicious', 'infected'].includes(status)) document.status = 'quarantined'; if (!unchanged) document.statusHistory.push({ from: previous, to: document.status, changedBy: actor, reason, adminOverride: true }); await document.save(); if (!unchanged && ['suspicious', 'infected'].includes(status)) await publishQuarantine(document); return serializeAdminDocument(document); };
