import mongoose from 'mongoose';
import { env } from '../config/env.js';
import { CANDIDATE_VISIBLE_OFFER_STATUSES } from '../constants/offer.js';
import { Application } from '../models/Application.js';
import { AssessmentAttempt } from '../models/AssessmentAttempt.js';
import { AssessmentAssignment } from '../models/AssessmentAssignment.js';
import { CandidateProfile } from '../models/CandidateProfile.js';
import { Company } from '../models/Company.js';
import { Document } from '../models/Document.js';
import { InterviewProcess } from '../models/InterviewProcess.js';
import { Offer } from '../models/Offer.js';
import { RecruiterProfile } from '../models/RecruiterProfile.js';
import { AppError } from '../shared/errors/AppError.js';
import { serializeDocument, serializeVerificationDocument } from '../utils/documentSerializer.js';
import { buildPagination } from '../utils/pagination.js';
import { companyRecipients } from '../utils/notificationRecipients.js';
import { authorizeDocumentAccess } from './documentAccess.service.js';
import { downloadDocument as ownerDownload, getActiveUploadSession, replaceDocument, uploadDocument } from './document.service.js';
import { createSignedDownloadUrl } from './fileStorageProvider.service.js';
import { deleteDocumentAssetIfUnreferenced } from './documentRetention.service.js';
import { publishOptionalDomainEvent } from './domainEvent.service.js';
import { DOMAIN_EVENTS } from '../constants/domainEvents.js';

const defaultDocumentEventDependencies = { companyRecipients, publishOptionalDomainEvent };
let documentEventDependencies = { ...defaultDocumentEventDependencies };
export const configureDocumentEventDependencies = (overrides = {}) => { documentEventDependencies = { ...defaultDocumentEventDependencies, ...overrides }; };
export const resetDocumentEventDependencies = () => { documentEventDependencies = { ...defaultDocumentEventDependencies }; };

const ACTIVE = { status: 'active', isCurrent: true };
const APPLICATION_CATEGORIES = ['resume', 'cover-letter', 'certificate', 'identity-document', 'education-document', 'experience-document', 'portfolio-document', 'application-document'];
const VERIFIABLE = ['certificate', 'identity-document', 'education-document', 'experience-document', 'application-document'];
const LOCKED_APPLICATION = ['withdrawn', 'rejected', 'hired', 'offer-declined'];
const ATTEMPT_UPLOAD_STATUSES = ['not-started', 'in-progress'];
const OFFER_VISIBLE = CANDIDATE_VISIBLE_OFFER_STATUSES;
const candidateCanViewOfferDocuments = (offer) => OFFER_VISIBLE.includes(offer.status) && (offer.status !== 'withdrawn' || Boolean(offer.sentAt));

const assertSession = async (user, id, category, entityType, entityId) => {
  const session = await getActiveUploadSession(user, id);
  if (session.category !== category || session.entityType !== entityType || !session.entityId.equals(entityId)) throw new AppError('Upload session does not match this resource', 400);
  return session;
};
const current = (filter) => Document.findOne({ ...filter, ...ACTIVE });
const signed = (document) => createSignedDownloadUrl({ publicId: document.storage.publicId, resourceType: document.storage.resourceType, expiresAt: new Date(Date.now() + env.FILE_SIGNED_URL_TTL_SECONDS * 1000), attachment: true });
const cleanup = (document) => deleteDocumentAssetIfUnreferenced(document).catch(() => null);

const profileConfig = {
  resume: { role: 'candidate', model: CandidateProfile, reference: 'resumeDocument', entityType: 'candidate-profile', category: 'resume', access: 'private' },
  candidatePhoto: { role: 'candidate', model: CandidateProfile, reference: 'profilePhotoDocument', entityType: 'candidate-profile', category: 'profile-photo', access: 'private' },
  recruiterPhoto: { role: 'recruiter', model: RecruiterProfile, reference: 'profilePhotoDocument', entityType: 'recruiter-profile', category: 'profile-photo', access: 'private' },
};
const profileFor = async (user, config) => { if (user.role !== config.role) throw new AppError('This document operation is not permitted', 403); const profile = await config.model.findOne({ user: user.id }); if (!profile) throw new AppError('Profile not found', 404); return profile; };
export const uploadProfileAsset = async (user, input, file, kind, replace = false) => {
  const config = profileConfig[kind]; const profile = await profileFor(user, config);
  await assertSession(user, input.uploadSessionId, config.category, config.entityType, profile.id);
  const previous = await current({ owner: user.id, category: config.category, entityType: config.entityType, entityId: profile.id });
  if (replace && !previous) throw new AppError('Current document not found', 404);
  if (!replace && previous) throw new AppError('A current document already exists; use replace', 409);
  const overrides = { access: config.access, reference: { model: config.model, id: profile.id, field: config.reference } };
  const document = replace ? await replaceDocument(user, previous.id, { ...input, category: config.category }, file, overrides) : await uploadDocument(user, { ...input, category: config.category }, file, null, overrides);
  if (replace && kind !== 'resume') await cleanup(previous);
  return serializeDocument(document);
};
export const getProfileAsset = async (user, kind) => { const config = profileConfig[kind]; const profile = await profileFor(user, config); const document = await current({ _id: profile[config.reference], owner: user.id, category: config.category }); if (!document) throw new AppError('Document not found', 404); return serializeDocument(document); };
export const deleteProfileAsset = async (user, kind) => { const config = profileConfig[kind]; const profile = await profileFor(user, config); const document = await current({ _id: profile[config.reference], owner: user.id }); if (!document) throw new AppError('Document not found', 404); const activeReference = kind === 'resume' && await Application.exists({ resumeDocument: document.id, status: { $nin: LOCKED_APPLICATION } }); if (activeReference) throw new AppError('Resume is retained by an active application', 409); const retained = kind === 'resume' && await Application.exists({ resumeDocument: document.id }); const status = retained ? 'archived' : 'deleted'; const databaseSession = await mongoose.startSession(); try { await databaseSession.withTransaction(async () => { const changed = await Document.updateOne({ _id: document.id, status: 'active', isCurrent: true }, { $set: { status, isCurrent: false, ...(retained ? { archivedAt: new Date() } : { deletedAt: new Date() }) }, $push: { statusHistory: { from: 'active', to: status, changedBy: user.id, reason: 'Profile document removed' } } }, { session: databaseSession }); const cleared = await config.model.updateOne({ _id: profile.id, [config.reference]: document.id }, { $set: { [config.reference]: null } }, { session: databaseSession }); if (!changed.modifiedCount || !cleared.modifiedCount) throw new AppError('Document reference changed during deletion', 409, 'DOCUMENT_REFERENCE_CONFLICT'); }); } finally { await databaseSession.endSession(); } document.status = status; document.isCurrent = false; if (!retained) await cleanup(document); return serializeDocument(document); };

export const uploadCompanyLogo = async (user, company, input, file, replace = false) => {
  await assertSession(user, input.uploadSessionId, 'company-logo', 'company', company.id);
  const previous = await current({ company: company.id, category: 'company-logo', entityType: 'company', entityId: company.id });
  if (replace && !previous) throw new AppError('Current company logo not found', 404); if (!replace && previous) throw new AppError('A company logo already exists; use replace', 409);
  const overrides = { company: company.id, access: 'public-profile', entityType: 'company', entityId: company.id, reference: { model: Company, id: company.id, field: 'logoDocument' } };
  const document = replace ? await replaceDocument(user, previous.id, { ...input, category: 'company-logo' }, file, overrides) : await uploadDocument(user, { ...input, category: 'company-logo' }, file, null, overrides);
  if (replace) await cleanup(previous); return serializeDocument(document);
};
export const getCompanyLogo = async (company) => { const document = await current({ _id: company.logoDocument, company: company.id, category: 'company-logo' }); if (!document) throw new AppError('Company logo not found', 404); return serializeDocument(document); };
export const deleteCompanyLogo = async (user, company) => { const document = await current({ _id: company.logoDocument, company: company.id }); if (!document) throw new AppError('Company logo not found', 404); const databaseSession = await mongoose.startSession(); try { await databaseSession.withTransaction(async () => { const changed = await Document.updateOne({ _id: document.id, status: 'active', isCurrent: true }, { $set: { status: 'deleted', isCurrent: false, deletedAt: new Date() }, $push: { statusHistory: { from: 'active', to: 'deleted', changedBy: user.id, reason: 'Company logo deleted' } } }, { session: databaseSession }); const cleared = await Company.updateOne({ _id: company.id, logoDocument: document.id }, { $set: { logoDocument: null } }, { session: databaseSession }); if (!changed.modifiedCount || !cleared.modifiedCount) throw new AppError('Company logo reference changed during deletion', 409, 'DOCUMENT_REFERENCE_CONFLICT'); }); } finally { await databaseSession.endSession(); } document.status = 'deleted'; document.isCurrent = false; await cleanup(document); return serializeDocument(document); };

const candidateApplication = async (user, id, writable = false) => { const application = await Application.findOne({ _id: id, candidate: user.id, isArchived: false }); if (!application) throw new AppError('Application not found', 404); if (writable && LOCKED_APPLICATION.includes(application.status)) throw new AppError('Application documents are locked', 409); return application; };
export const uploadApplicationDocument = async (user, applicationId, input, file, replacedId) => { const application = await candidateApplication(user, applicationId, true); if (!APPLICATION_CATEGORIES.includes(input.category)) throw new AppError('Document category is not permitted for applications', 400); await assertSession(user, input.uploadSessionId, input.category, 'application', application.id); let previous; if (replacedId) { previous = await Document.findOne({ _id: replacedId, owner: user.id, entityType: 'application', entityId: application.id, ...ACTIVE }); if (!previous) throw new AppError('Document not found', 404); } const required = VERIFIABLE.includes(input.category); const verification = required ? { required: true, status: 'pending', submittedAt: new Date() } : { required: false, status: 'not-required' }; const synchronizeResume = input.category === 'resume' && (!application.resumeDocument || application.resumeDocument.equals(previous?.id)); const overrides = { company: application.company, entityType: 'application', entityId: application.id, access: input.access ?? 'company-private', verification, ...(synchronizeResume && { reference: { model: Application, id: application.id, field: 'resumeDocument' } }) }; const document = previous ? await replaceDocument(user, previous.id, input, file, overrides) : await uploadDocument(user, input, file, null, overrides); if (required) { try { const recipients = await documentEventDependencies.companyRecipients(application.company, 'documents.verify'); if (recipients.length) await documentEventDependencies.publishOptionalDomainEvent({ type: DOMAIN_EVENTS.DOCUMENT_VERIFICATION_REQUESTED, company: String(application.company), recipientIds: recipients.map(String), payload: { documentId: String(document.id), applicationId: String(application.id), candidateId: String(user.id), companyId: String(application.company), category: document.category, displayName: document.displayName, actionUrl: `/recruiter/documents/verification/${document.id}` }, deduplicationKey: `document.verification-requested:${document.id}` }); } catch { /* Optional notification resolution cannot reverse a committed upload. */ } } return serializeDocument(document); };
export const listCandidateApplicationDocuments = async (user, id) => { const application = await candidateApplication(user, id); return (await Document.find({ owner: user.id, entityType: 'application', entityId: application.id, status: 'active' })).map(serializeDocument); };
const companyApplication = async (company, id) => { const application = await Application.findOne({ _id: id, company, isArchived: false }); if (!application) throw new AppError('Application not found', 404); return application; };
export const listManagedApplicationDocuments = async (company, id) => { const application = await companyApplication(company, id); return (await Document.find({ company, entityType: 'application', entityId: application.id, status: 'active', access: { $in: ['company-private', 'candidate-visible'] } })).map(serializeDocument); };
export const getManagedApplicationDocument = async (company, applicationId, documentId) => { await companyApplication(company, applicationId); return serializeDocument(await scopedDocument({ _id: documentId, company, entityType: 'application', entityId: applicationId, access: { $in: ['company-private', 'candidate-visible'] } })); };

const attemptForCandidate = async (user, id, writable = false) => { const attempt = await AssessmentAttempt.findOne({ _id: id, candidate: user.id }); if (!attempt) throw new AppError('Assessment attempt not found', 404); const assignment = await AssessmentAssignment.findById(attempt.assignment); if (!assignment) throw new AppError('Assessment assignment not found', 404); const now = new Date(); if (writable && (!ATTEMPT_UPLOAD_STATUSES.includes(attempt.status) || attempt.expiresAt <= now || assignment.expiresAt <= now || assignment.status === 'cancelled')) throw new AppError('Assessment attachments are no longer accepted', 409, 'DOCUMENT_CONFLICT'); return { attempt, assignment }; };
export const uploadAttemptDocument = async (user, id, input, file) => { const { attempt, assignment } = await attemptForCandidate(user, id, true); const configuration = assignment.assessmentSnapshot.attachments ?? { enabled: false }; if (!configuration.enabled) throw new AppError('Assessment attachments are not enabled', 409, 'ATTACHMENTS_NOT_ENABLED'); if (!configuration.allowedMimeTypes?.includes(file.mimetype)) throw new AppError('File type is not allowed for this assessment', 400, 'DOCUMENT_CONFLICT'); if (file.size > configuration.maximumFileBytes) throw new AppError('Attachment file-size limit exceeded', 413, 'ATTACHMENT_LIMIT_REACHED'); const existing = await Document.find({ owner: user.id, entityType: 'assessment-attempt', entityId: attempt.id, status: 'active' }); if (existing.length >= configuration.maximumFiles) throw new AppError('Assessment attachment count limit reached', 413, 'ATTACHMENT_LIMIT_REACHED'); if (existing.reduce((sum, item) => sum + item.sizeBytes, 0) + file.size > configuration.maximumTotalBytes) throw new AppError('Assessment attachment total-size limit exceeded', 413, 'ATTACHMENT_TOTAL_SIZE_EXCEEDED'); await assertSession(user, input.uploadSessionId, 'assessment-attachment', 'assessment-attempt', attempt.id); return serializeDocument(await uploadDocument(user, { ...input, category: 'assessment-attachment' }, file, null, { company: attempt.company, access: 'company-private', entityType: 'assessment-attempt', entityId: attempt.id })); };
export const listAttemptDocuments = async (actor, id, company) => { const attempt = company ? await AssessmentAttempt.findOne({ _id: id, company }) : (await attemptForCandidate(actor, id)).attempt; if (!attempt) throw new AppError('Assessment attempt not found', 404); return (await Document.find({ entityType: 'assessment-attempt', entityId: attempt.id, status: 'active', ...(company && { company }) })).map(serializeDocument); };

const processFor = async (id, company) => { const process = await InterviewProcess.findOne({ _id: id, ...(company && { company }), isArchived: false }); if (!process) throw new AppError('Interview process not found', 404); return process; };
export const uploadInterviewDocument = async (user, company, id, input, file, replacedId) => { const process = await processFor(id, company); await assertSession(user, input.uploadSessionId, 'interview-attachment', 'interview-process', process.id); if (/password|token|secret|credential/i.test(input.purpose)) throw new AppError('Sensitive meeting credentials are not permitted', 400); let previous; if (replacedId) { previous = await current({ _id: replacedId, company, category: 'interview-attachment', entityType: 'interview-process', entityId: process.id }); if (!previous) throw new AppError('Interview attachment cannot be replaced', 409, 'DOCUMENT_REPLACEMENT_NOT_ALLOWED'); } const overrides = { company, access: input.access ?? previous?.access, entityType: 'interview-process', entityId: process.id }; const document = previous ? await replaceDocument(user, previous.id, { ...input, category: 'interview-attachment' }, file, overrides) : await uploadDocument(user, { ...input, category: 'interview-attachment' }, file, null, overrides); if (previous) await cleanup(previous); return serializeDocument(document); };
export const listInterviewDocuments = async (actor, id, company) => { const process = await processFor(id, company); if (!company && (!process.candidate.equals(actor.id) || !['active', 'completed'].includes(process.status))) throw new AppError('Interview process not found', 404); return (await Document.find({ entityType: 'interview-process', entityId: process.id, status: 'active', access: company ? { $in: ['company-private', 'candidate-visible'] } : 'candidate-visible' })).map(serializeDocument); };

const offerFor = async (id, company, candidate) => { const offer = await Offer.findOne({ _id: id, ...(company && { company }), ...(candidate && { candidate }), isArchived: false }); if (!offer) throw new AppError('Offer not found', 404); return offer; };
export const uploadOfferDocument = async (user, company, id, input, file, replacedId) => { const offer = await offerFor(id, company); await assertSession(user, input.uploadSessionId, 'offer-document', 'offer', offer.id); let previous; if (replacedId) { previous = await current({ _id: replacedId, company, entityType: 'offer', entityId: offer.id }); if (!previous) throw new AppError('Document not found', 404); } const overrides = { company, access: input.access, entityType: 'offer', entityId: offer.id }; return serializeDocument(previous ? await replaceDocument(user, previous.id, { ...input, category: 'offer-document' }, file, overrides) : await uploadDocument(user, { ...input, category: 'offer-document' }, file, null, overrides)); };
export const listOfferDocuments = async (actor, id, company) => { const offer = await offerFor(id, company, company ? undefined : actor.id); if (!company && !candidateCanViewOfferDocuments(offer)) throw new AppError('Offer not found', 404); return (await Document.find({ entityType: 'offer', entityId: offer.id, status: 'active', access: company ? { $in: ['company-private', 'candidate-visible'] } : 'candidate-visible' })).map(serializeDocument); };

export const entityDownload = async (actor, documentId, context) => { const document = await Document.findById(documentId); if (!document) throw new AppError('Document not found', 404); authorizeDocumentAccess({ actor, document, action: 'download', context }); return signed(document); };
export const ownerEntityDownload = ownerDownload;

export const listVerification = async (company, query) => { const filter = { company, 'verification.status': query.status ?? 'pending', isCurrent: true, status: 'active' }; if (query.category) filter.category = query.category; if (query.applicationId) filter.entityId = query.applicationId; if (query.candidateId) filter.owner = query.candidateId; if (query.uploadedFrom || query.uploadedTo) filter.createdAt = { ...(query.uploadedFrom && { $gte: query.uploadedFrom }), ...(query.uploadedTo && { $lte: query.uploadedTo }) }; const [documents, total] = await Promise.all([Document.find(filter).sort(query.sort === 'oldest' ? { createdAt: 1 } : { createdAt: -1 }).skip((query.page - 1) * query.limit).limit(query.limit), Document.countDocuments(filter)]); return { documents: documents.map(serializeVerificationDocument), pagination: buildPagination(query.page, query.limit, total) }; };
export const getVerification = async (company, id) => { const document = await Document.findOne({ _id: id, company, entityType: 'application', 'verification.required': true }); if (!document) throw new AppError('Document not found', 404); return serializeVerificationDocument(document, true); };
export const decideVerification = async (user, company, id, decision, input) => { const document = await Document.findOne({ _id: id, company, entityType: 'application', status: 'active', isCurrent: true, 'verification.status': 'pending' }); if (!document) throw new AppError('Pending document not found', 404); document.verification.status = decision; document.verification.reviewedAt = new Date(); document.verification.reviewedBy = user.id; document.verification.candidateSafeReason = decision === 'rejected' ? input.reason : undefined; document.verification.privateNotes = input.notes; document.statusHistory.push({ from: 'verification-pending', to: `verification-${decision}`, changedBy: user.id, reason: decision === 'rejected' ? input.reason : 'Document verified' }); await document.save(); const application = await Application.findById(document.entityId).populate('company', 'name'); await publishOptionalDomainEvent({ type: decision === 'verified' ? DOMAIN_EVENTS.DOCUMENT_VERIFIED : DOMAIN_EVENTS.DOCUMENT_REJECTED, company: String(company), recipientIds: [String(document.owner)], payload: { documentId: String(document.id), applicationId: String(document.entityId), candidateId: String(document.owner), companyId: String(company), companyName: application?.company?.name, category: document.category, displayName: document.displayName, reason: decision === 'rejected' ? input.reason : undefined, actionUrl: `/candidate/applications/${document.entityId}` }, deduplicationKey: `document.${decision}:${document.id}` }); return serializeVerificationDocument(document, true); };

const scopedDocument = async (filter) => { const document = await Document.findOne({ ...filter, status: 'active', isCurrent: true }); if (!document) throw new AppError('Document not found', 404); return document; };
export const downloadManagedApplicationDocument = async (actor, company, applicationId, documentId) => { await companyApplication(company, applicationId); const document = await scopedDocument({ _id: documentId, company, entityType: 'application', entityId: applicationId, access: { $in: ['company-private', 'candidate-visible'] } }); authorizeDocumentAccess({ actor, document, action: 'download', context: { company, recruiter: true } }); return signed(document); };
export const downloadManagedAttemptDocument = async (actor, company, attemptId, documentId) => { const attempt = await AssessmentAttempt.findOne({ _id: attemptId, company }); if (!attempt) throw new AppError('Assessment attempt not found', 404); const document = await scopedDocument({ _id: documentId, company, entityType: 'assessment-attempt', entityId: attempt.id }); authorizeDocumentAccess({ actor, document, action: 'download', context: { company, recruiter: true } }); return signed(document); };
export const downloadInterviewDocument = async (actor, processId, documentId, company) => { const interview = await processFor(processId, company); if (!company && !['active', 'completed'].includes(interview.status)) throw new AppError('Interview process not found', 404); const document = await scopedDocument({ _id: documentId, entityType: 'interview-process', entityId: interview.id, ...(company ? { company } : { access: 'candidate-visible' }) }); authorizeDocumentAccess({ actor, document, action: 'download', context: company ? { company, recruiter: true } : { candidate: true, interview } }); return signed(document); };
export const updateInterviewAccess = async (company, processId, documentId, access) => { await processFor(processId, company); const document = await scopedDocument({ _id: documentId, company, entityType: 'interview-process', entityId: processId }); document.access = access; await document.save(); return serializeDocument(document); };
export const downloadOfferDocument = async (actor, offerId, documentId, company) => { const offer = await offerFor(offerId, company, company ? undefined : actor.id); if (!company && !candidateCanViewOfferDocuments(offer)) throw new AppError('Offer not found', 404); const document = await scopedDocument({ _id: documentId, entityType: 'offer', entityId: offer.id, ...(company ? { company } : { access: 'candidate-visible' }) }); authorizeDocumentAccess({ actor, document, action: 'download', context: company ? { company, recruiter: true } : { candidate: true, offer } }); return signed(document); };
