import { Router } from 'express';
import { USER_ROLES } from '../constants/roles.js';
import * as admin from '../controllers/adminNotification.controller.js';
import * as inbox from '../controllers/notification.controller.js';
import * as preferences from '../controllers/notificationPreference.controller.js';
import { authenticate } from '../middleware/auth.js';
import { authorizeRoles } from '../middleware/authorizeRoles.js';
import * as schemas from '../validators/notification.validator.js';
import { validateBody, validateParams, validateQuery } from '../validators/validate.js';

export const notificationRouter = Router();
notificationRouter.use(authenticate);
const adminOnly = authorizeRoles(USER_ROLES.ADMIN);
notificationRouter.post('/admin/process-outbox', adminOnly, validateBody(schemas.processBody), admin.processOutbox);
notificationRouter.post('/admin/templates', adminOnly, validateBody(schemas.templateBody), admin.createTemplate);
notificationRouter.get('/admin/templates', adminOnly, admin.listTemplates);
notificationRouter.get('/admin/templates/:templateId', adminOnly, validateParams(schemas.templateIdParams), admin.getTemplate);
notificationRouter.patch('/admin/templates/:templateId', adminOnly, validateParams(schemas.templateIdParams), validateBody(schemas.templateUpdateBody), admin.updateTemplate);
notificationRouter.post('/admin/templates/:templateId/clone', adminOnly, validateParams(schemas.templateIdParams), admin.cloneTemplate);
notificationRouter.patch('/admin/templates/:templateId/deactivate', adminOnly, validateParams(schemas.templateIdParams), admin.deactivateTemplate);
notificationRouter.post('/admin/templates/:templateId/preview', adminOnly, validateParams(schemas.templateIdParams), validateBody(schemas.previewBody), admin.previewTemplate);
notificationRouter.get('/admin/email-logs', adminOnly, validateQuery(schemas.adminQuery), admin.emailLogs);
notificationRouter.get('/admin/outbox', adminOnly, validateQuery(schemas.adminQuery), admin.outbox);
notificationRouter.patch('/admin/outbox/:eventId/retry', adminOnly, validateParams(schemas.eventIdParams), admin.retry);
notificationRouter.patch('/admin/outbox/:eventId/cancel', adminOnly, validateParams(schemas.eventIdParams), admin.cancel);
notificationRouter.get('/admin', adminOnly, validateQuery(schemas.adminQuery), admin.listNotifications);
notificationRouter.get('/admin/:notificationId', adminOnly, validateParams(schemas.notificationIdParams), admin.getNotification);
notificationRouter.get('/unread-count', inbox.unreadCount);
notificationRouter.get('/preferences', preferences.get);
notificationRouter.put('/preferences', validateBody(schemas.preferenceBody), preferences.update);
notificationRouter.patch('/preferences/reset', preferences.reset);
notificationRouter.patch('/read-all', inbox.readAll);
notificationRouter.patch('/archive-all', inbox.archiveAll);
notificationRouter.patch('/bulk/read', validateBody(schemas.bulkBody), inbox.bulkRead);
notificationRouter.patch('/bulk/archive', validateBody(schemas.bulkBody), inbox.bulkArchive);
notificationRouter.get('/', validateQuery(schemas.inboxQuery), inbox.list);
notificationRouter.get('/:notificationId', validateParams(schemas.notificationIdParams), inbox.get);
notificationRouter.patch('/:notificationId/read', validateParams(schemas.notificationIdParams), inbox.markRead);
notificationRouter.patch('/:notificationId/unread', validateParams(schemas.notificationIdParams), inbox.markUnread);
notificationRouter.patch('/:notificationId/archive', validateParams(schemas.notificationIdParams), inbox.archive);
notificationRouter.patch('/:notificationId/unarchive', validateParams(schemas.notificationIdParams), inbox.unarchive);
notificationRouter.delete('/:notificationId', validateParams(schemas.notificationIdParams), inbox.remove);
