import { ANALYTICS_MAX_BUCKETS, ANALYTICS_MAX_RANGE_DAYS } from '../constants/analytics.js';
import { AppError } from '../shared/errors/AppError.js';

const day = 86400000;
const startDay = (date) => new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate()));
const endDay = (date) => new Date(startDay(date).getTime() + day - 1);
const addMonths = (date, amount) => new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth() + amount, 1));
const presetRange = (preset, now) => { const today = startDay(now); const ranges = { today: [today, endDay(today)], yesterday: [new Date(today - day), new Date(today - 1)], 'last-7-days': [new Date(today - 6 * day), endDay(today)], 'last-30-days': [new Date(today - 29 * day), endDay(today)], 'last-90-days': [new Date(today - 89 * day), endDay(today)], 'this-month': [addMonths(today, 0), endDay(now)], 'last-month': [addMonths(today, -1), new Date(addMonths(today, 0) - 1)], 'this-quarter': [new Date(Date.UTC(now.getUTCFullYear(), Math.floor(now.getUTCMonth() / 3) * 3, 1)), endDay(now)], 'this-year': [new Date(Date.UTC(now.getUTCFullYear(), 0, 1)), endDay(now)], 'all-time': [new Date(0), endDay(now)] }; return ranges[preset]; };
const automaticInterval = (milliseconds) => milliseconds <= 2 * day ? 'hour' : milliseconds <= 90 * day ? 'day' : milliseconds <= 366 * day ? 'week' : 'month';
export const resolveAnalyticsRange = (query, now = new Date()) => { const preset = query.preset ?? (!query.from && !query.to ? 'last-30-days' : undefined); let from; let to; if (preset) [from, to] = presetRange(preset, now); else { from = new Date(query.from); to = new Date(query.to); } if (!(from < to)) throw new AppError('Analytics date range is invalid', 400, 'ANALYTICS_INVALID_RANGE'); if (preset !== 'all-time' && to - from > ANALYTICS_MAX_RANGE_DAYS * day) throw new AppError('Analytics date range is too large', 400, 'ANALYTICS_RANGE_TOO_LARGE'); const interval = query.interval ?? automaticInterval(to - from); const duration = to - from + 1; return { from, to, preset: preset ?? 'custom', interval, timezone: 'UTC', previous: { from: new Date(from.getTime() - duration), to: new Date(from.getTime() - 1) } }; };
const floorBucket = (date, interval) => { if (interval === 'hour') return new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate(), date.getUTCHours())); if (interval === 'day') return startDay(date); if (interval === 'week') { const value = startDay(date); return new Date(value.getTime() - ((value.getUTCDay() + 6) % 7) * day); } return new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), 1)); };
const nextBucket = (date, interval) => interval === 'hour' ? new Date(date.getTime() + 3600000) : interval === 'day' ? new Date(date.getTime() + day) : interval === 'week' ? new Date(date.getTime() + 7 * day) : addMonths(date, 1);
export const fillTimeSeriesBuckets = ({ data, from, to, interval, valueKey = 'value' }) => { const values = new Map(data.map((row) => [new Date(row.date ?? row._id).toISOString(), Number(row[valueKey] ?? row.value ?? row.count ?? 0)])); const output = []; for (let cursor = floorBucket(from, interval); cursor <= to; cursor = nextBucket(cursor, interval)) { if (output.length >= ANALYTICS_MAX_BUCKETS) throw new AppError('Analytics range produces too many buckets', 400, 'ANALYTICS_RANGE_TOO_LARGE'); const date = cursor.toISOString(); output.push({ date, value: values.get(date) ?? 0 }); } return output; };
export const mongoDateFormat = (interval) => interval === 'hour' ? '%Y-%m-%dT%H:00:00.000Z' : interval === 'day' ? '%Y-%m-%dT00:00:00.000Z' : interval === 'week' ? '%G-W%V' : '%Y-%m-01T00:00:00.000Z';
