import { getRemainingSeconds } from './assessmentTiming.js';
const publicQuestion = (question, optionOrder) => { const output = { questionId: question.questionId, type: question.type, title: question.title, prompt: question.prompt, description: question.description, marks: question.marks, isRequired: question.isRequired, options: question.options }; if (optionOrder?.length) output.options = optionOrder.map((id) => question.options.find((item) => item.id === id)).filter(Boolean); if (question.coding) output.coding = { languageSupport: question.coding.languageSupport, starterCode: question.coding.starterCode, functionName: question.coding.functionName, testCases: question.coding.testCases.filter((item) => !item.isHidden).map(({ expectedOutput: _expected, ...item }) => item) }; if (question.deliverable) output.deliverable = { type: question.deliverable.type, instructions: question.deliverable.instructions, allowedFormats: question.deliverable.allowedFormats, maxFiles: question.deliverable.maxFiles, maxFileSizeBytes: question.deliverable.maxFileSizeBytes, referenceAssets: question.deliverable.referenceAssets }; if (question.rubric?.criteria?.length) output.rubricCriteria = question.rubric.criteria.map((c) => ({ name: c.name, maxMarks: c.maxMarks, weight: c.weight })); return output; };
export const serializeCandidateAssignment = (assignment) => {
  let status = assignment.status;
  if (['assigned', 'available', 'in-progress'].includes(status) && assignment.expiresAt && new Date(assignment.expiresAt) < new Date()) {
    status = 'expired';
  }
  return { id: assignment.id, assessmentId: assignment.assessment, title: assignment.assessmentSnapshot.title, description: assignment.assessmentSnapshot.description, instructions: assignment.assessmentSnapshot.instructions, durationMinutes: assignment.assessmentSnapshot.durationMinutes, totalMarks: assignment.assessmentSnapshot.totalMarks, attemptsUsed: assignment.attemptsUsed, attemptsRemaining: Math.max(0, assignment.assessmentSnapshot.maximumAttempts - assignment.attemptsUsed), availableFrom: assignment.availableFrom, expiresAt: assignment.expiresAt, status, latestAttempt: assignment.latestAttempt };
};
export const serializeActiveAttempt = (attempt, snapshot) => ({ id: attempt.id, status: attempt.status, startedAt: attempt.startedAt, expiresAt: attempt.expiresAt, remainingSeconds: getRemainingSeconds(attempt), allowBackNavigation: snapshot.allowBackNavigation, seed: attempt.seed, questions: attempt.questionOrder.map((id) => publicQuestion(snapshot.questions.find((question) => question.questionId.toString() === id.toString()), attempt.optionOrders?.[id.toString()])), answers: attempt.answers });
export const serializeCandidateResult = (attempt, assignment) => ({ score: attempt.evaluation.totalScore, totalMarks: assignment.assessmentSnapshot.totalMarks, percentage: attempt.evaluation.percentage, passed: attempt.evaluation.passed, completedAt: attempt.completedAt, questionResults: attempt.questionResults.map(({ questionId, questionType, marks, awardedMarks, feedback, codingResult, rubricScores }) => ({ questionId, questionType, marks, awardedMarks, feedback, ...(codingResult && { codingResult: { status: codingResult.status, passedTests: codingResult.passedTests, totalTests: codingResult.totalTests } }), ...(rubricScores?.length && { rubricScores: rubricScores.map(({ criterionName, awardedMarks: am, maxMarks }) => ({ criterionName, awardedMarks: am, maxMarks })) }) })) });
