# Generated by Selenium IDE and updated for Talvix automated testing
import os
import time
import pytest
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.chrome.options import Options as ChromeOptions
from selenium.webdriver.edge.options import Options as EdgeOptions
from selenium.webdriver.firefox.options import Options as FirefoxOptions

class TestRegister:
    def setup_method(self, method):
        # Support headless execution by default (can be toggled via SELENIUM_HEADLESS)
        headless = os.environ.get("SELENIUM_HEADLESS", "true").lower() in ("true", "1", "yes")

        driver = None
        # 1. Try Chrome
        try:
            options = ChromeOptions()
            if headless:
                options.add_argument("--headless=new")
            options.add_argument("--window-size=1280,1024")
            driver = webdriver.Chrome(options=options)
        except Exception:
            pass

        # 2. Try Edge
        if not driver:
            try:
                options = EdgeOptions()
                if headless:
                    options.add_argument("--headless=new")
                options.add_argument("--window-size=1280,1024")
                driver = webdriver.Edge(options=options)
            except Exception:
                pass

        # 3. Try Firefox
        if not driver:
            try:
                options = FirefoxOptions()
                if headless:
                    options.add_argument("-headless")
                driver = webdriver.Firefox(options=options)
            except Exception as e:
                pytest.fail(f"Could not initialize any browser driver (Chrome, Edge, Firefox): {e}")

        self.driver = driver
        self.vars = {}

    def teardown_method(self, method):
        if hasattr(self, "driver") and self.driver:
            self.driver.quit()

    def test_register(self):
        # Open the register page
        self.driver.get("http://localhost:5173/register")
        wait = WebDriverWait(self.driver, 10)

        # Wait until register form elements are visible
        fullname_input = wait.until(EC.presence_of_element_located((By.ID, "register-fullName")))
        fullname_input.clear()
        
        # Use a dynamic timestamped email to allow repeated test executions without duplicate email conflicts
        unique_email = f"test_user_{int(time.time())}@example.com"
        fullname_input.send_keys("Amal Babu")

        email_input = self.driver.find_element(By.ID, "register-email")
        email_input.clear()
        email_input.send_keys(unique_email)

        password_input = self.driver.find_element(By.ID, "register-password")
        password_input.clear()
        password_input.send_keys("Amal@12345")

        confirm_password_input = self.driver.find_element(By.ID, "register-confirmPassword")
        confirm_password_input.clear()
        confirm_password_input.send_keys("Amal@12345")

        # Select Terms Checkbox
        try:
            terms_checkbox = self.driver.find_element(By.CSS_SELECTOR, "input[name='agreeTerms']")
            if not terms_checkbox.is_selected():
                self.driver.execute_script("arguments[0].click();", terms_checkbox)
        except Exception:
            try:
                label = self.driver.find_element(By.CSS_SELECTOR, "label.tvx-choice")
                self.driver.execute_script("arguments[0].click();", label)
            except Exception:
                pass

        # Locate and click submit button
        submit_btn = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, "button[type='submit']")))
        self.driver.execute_script("arguments[0].scrollIntoView(true);", submit_btn)
        time.sleep(0.5)
        
        try:
            submit_btn.click()
        except Exception:
            self.driver.execute_script("arguments[0].click();", submit_btn)

        # Wait for form processing or page navigation
        time.sleep(3)
        current_url = self.driver.current_url
        print(f"Post-registration URL: {current_url}")
        assert self.driver.title is not None
        assert current_url != ""
